### ISSUE TITLE
[BUG] start-here 24 pixels icon in both Nordzy and Nordzy-dark are Apple logos.

### ISSUE THREAD

**Issue by darkshram** [alvatip/Nordzy-icon#1]
**Describe the bug**
start-here 24 pixels icon in both Nordzy and Nordzy-dark are Apple logos. The 16 and 22 size are Linux logo icons.

**Expected behaviour**
All start-here icons should be the same.

**Screenshots**
![Captura de pantalla_2021-08-11_22-08-20](https://user-images.githubusercontent.com/10327500/129132627-c393358d-cf50-44c8-befd-7832db6b2394.png)

**Additional context**
Also... the Linux Logo is nice, but I think a more generic and OS neutral logo would be better, like start-here logo from Zafiro icons.

**Comment by alvatip** [comment]
Hi, 
You're right, I must have missed it, thank you !
I will fix it this weekend ;)
By more generic and OS neutral, you mean something more *distribution oriented*, like a start-here-debian, start-here-fedora, start-here-ubuntu and so on ? Or more *desktop environment oriented*, like start-here-gnome, start-here-kde and so on ? 
Thanks

**Comment by darkshram** [comment]
Sorry, Zafiro was a bad example. I was thinking about something like these (from Tela icon theme):
![start-here](https://user-images.githubusercontent.com/10327500/129167477-9f8a0b2b-48b8-49e3-aa16-51d4c1abc995.png)
![start-here-light](https://user-images.githubusercontent.com/10327500/129169140-ad3f94d5-5ae9-425d-a490-37759146b49b.png)
Or something like these ones (from Numix icon theme):
![numix-start-here-dark](https://user-images.githubusercontent.com/10327500/129169586-78bfa2c6-4239-4ff1-963f-e1845a1540f7.png)
![numix-start-here-light](https://user-images.githubusercontent.com/10327500/129169601-cf865c4a-5c39-4ca3-aaf6-e8378ab44272.png)

**Comment by alvatip** [comment]
Ok I see now. 
Thanks, I will fix it !
