### ISSUE TITLE
[ICON] Dolphin search icon

### ISSUE THREAD

**Issue by TRPB** [alvatip/Nordzy-icon#10]
Application name: Dolphin (kde file manager)
Icon name if you know it: search?

![image](https://user-images.githubusercontent.com/2454540/149181852-ee36587d-f4d0-4392-9ece-74a20e0bcadd.png)

I'm not sure exactly where this icon is coming from, but as the only icon with a background it stands out. 

I want to replace the icon 2nd from last with your existing search.svg but I'm not sure what it's called or which folder it should be in.

I'd also prefer a standard 3 line menu icon than the dots in a circle, but that's not as much of an issue.

Thanks for these icons though, fantastic work! 

edit: I've just set `Inherits=breeze-dark` in the theme which fixes it (or at least uses the breeze search icon which fits in a lot better).

**Comment by alvatip** [comment]
Indeed, that is odd… 
So currently I tried reproducing this behavior, without success. The icon show correctly on my fedora using gnome, as well as on ubuntu 20 + KDE and Kubuntu 21… Furthermore, I did not noticed any errors in the icon theme (for now).
What is your distro ? I will create a VM to try it. And maybe also, how did you install the icon theme ? I hope to reproduce the issue this way.
Did you try completely removing the icons from your pc, clearing the icon cache, and then reinstalling it ?
In the meantime, I updated the three dots in a circle icon, it looks indeed better.
![image](https://user-images.githubusercontent.com/84344248/149624112-0790c6c0-2944-4e9c-aac7-969e674119c1.png)
