### ISSUE TITLE
[ICON] Plexamp

### ISSUE THREAD

**Issue by rogerizo** [alvatip/Nordzy-icon#100]
Application name: Plexamp
Icon name if you know it: com.plexamp.Plexamp
Original icon image: 
![com plexamp Plexamp](https://user-images.githubusercontent.com/7864805/207649449-cd13c5e2-26c8-4389-93f1-eb16cc2f448d.png)

Use tray? no

Small description and/or a link to the official webpage:
https://plexamp.com/

Thanks!

**Comment by alvatip** [comment]
I just added the icon. It should work properly, if this is not the case, feel free to reopen the issue and I will fix it :wink:
