### ISSUE TITLE
[ICON] Some KDE apps

### ISSUE THREAD

**Issue by Teatov** [alvatip/Nordzy-icon#101]
Application name: KolourPaint
Icon name if you know it: org.kde.kolourpaint
Original icon image: 
![kolourpaint](https://user-images.githubusercontent.com/79892286/208582140-3ee519ba-20a6-434b-8bc4-46e3ec2820db.svg)
Use tray? no
Small description and/or a link to the official webpage: A simple image editor https://apps.kde.org/ru/kolourpaint/

Application name: Elisa
Icon name if you know it: org.kde.elisa
Original icon image: 
![elisa](https://user-images.githubusercontent.com/79892286/208582432-80cf3441-388f-4813-9d51-477476a618aa.svg)
Use tray? no
Small description and/or a link to the official webpage: A simple music player https://apps.kde.org/elisa/

Application name: Okular
Icon name if you know it: org.kde.okular
Original icon image:
![okular](https://user-images.githubusercontent.com/79892286/208582776-d573aef2-e7fb-467e-9da4-48eb52c5c14f.svg)
Use tray? no
Small description and/or a link to the official webpage: Document viewer https://apps.kde.org/okular/

**Comment by alvatip** [comment]
Thanks for your requests. 
I added the icons, everything should work properly, if not feel free to reopen this issue :wink:

**Comment by Teatov** [comment]
Oops, actually they also need alias names without the "org.kde" part, sorry. That will be just "kolourpaint", "elisa" and "okular"
