### ISSUE TITLE
[ICON]

### ISSUE THREAD

**Issue by Randdose** [alvatip/Nordzy-icon#103]
Application name: waydroid
Icon name if you know it: 
Original icon image: 
![waydroid_icon_sm](https://user-images.githubusercontent.com/97728376/210019522-ad22c9e5-e714-4f55-a74d-a99b5b6f5cbf.png)

Use tray? no

Small description and/or a link to the official webpage: container for running full android system on linux: https://waydro.id/

tried making one: 
![_Layer 1](https://user-images.githubusercontent.com/97728376/210019301-3fc7433b-86f9-4f76-86d6-68919f0eb753.svg)

**Comment by alvatip** [comment]
Thanks. 
I added the icon (name: waydroid). I have not tested it yet but on the github project of waydroid, it looks like the .desktop file is looking for the icon in `/usr/lib/waydroid/data/AppIcon.png` if this is the case it will have to be updated manually. 
Could you try the theme installing it by cloning the repo and installing the theme using the ./install shell script ? I will also try it on my VM when I have the time :wink:

**Comment by Randdose** [comment]
thank you very much, it's working perfectly.
sorry for the late response.
