### ISSUE TITLE
[ICON] Spectacle

### ISSUE THREAD

**Issue by arun54321** [alvatip/Nordzy-icon#11]
Application name: Spectacle
Icon name if you know it: 
Original icon image: 
Use tray?
Small description and/or a link to the official webpage: https://apps.kde.org/spectacle/

**Comment by alvatip** [comment]
Icon is added :wink: 
I will create a new release in 2 weeks, meanwhile you can use the latest version by cloning the repo and using the installation script!
Preview: 
![image](https://user-images.githubusercontent.com/84344248/152350513-2c05a05d-a1d9-4107-8c06-c5256005cb51.png)

**Comment by arun54321** [comment]
Thankyou.
