### ISSUE TITLE
[ICON] Feather, Sparrow, Bisq

### ISSUE THREAD

**Issue by saltrafael** [alvatip/Nordzy-icon#112]
Application name: Feather Wallet
Original icon image: 
![image](https://user-images.githubusercontent.com/76502841/217903442-262d401d-2441-482c-991b-9fd64ac87e5f.png)
Use tray? yes
Small description and/or a link to the official webpage: https://github.com/feather-wallet/feather

Application name: Sparrow Wallet
Original icon image: 
![image](https://user-images.githubusercontent.com/76502841/217904277-1035368e-8c03-4b05-b331-c6077d6cdf21.png)
Use tray? no
Small description and/or a link to the official webpage: https://github.com/sparrowwallet/sparrow

Application name: Bisq
Original icon image: 
![image](https://user-images.githubusercontent.com/76502841/217904831-f3ddc9e3-7d4f-411c-ab81-777fc03000f7.png)
Use tray? no
Small description and/or a link to the official webpage: https://github.com/bisq-network/bisq

**Comment by alvatip** [comment]
I will add them in the following days :wink:

**Comment by alvatip** [comment]
Hey, 
I added the three icons in the last commit, they should work fine :wink: 
Feel free to reach out to me here if there is something going wrong

PS: It seems that feather is only distributed as AppImage, his .desktop file might need a manual update for the icon to be displayed properly.
