### ISSUE TITLE
[ICON] SimpleScreenRecorder

### ISSUE THREAD

**Issue by Teatov** [alvatip/Nordzy-icon#114]
Application name: SimpleScreenRecorder
Small description and/or a link to the official webpage: A program to record screen activity to video. https://www.maartenbaert.be/simplescreenrecorder/
Use tray? No.

Icon name if you know it: simplescreenrecorder, simplescreenrecorder-idle
Original icon image:
![simplescreenrecorder](https://user-images.githubusercontent.com/79892286/218966402-07bcf003-5091-4956-ab6b-0c5bdf78b6b2.svg)

Icon name if you know it: simplescreenrecorder-recording
Original icon image:
![simplescreenrecorder-recording](https://user-images.githubusercontent.com/79892286/218966564-b8d2821d-4ef5-4e2f-be58-5537fba92420.svg)

Icon name if you know it: simplescreenrecorder-paused
Original icon image:
![simplescreenrecorder-paused](https://user-images.githubusercontent.com/79892286/218966663-d2f70c8c-b73f-4f25-864f-7b50a4e5b916.svg)

Icon name if you know it: simplescreenrecorder-error
Original icon image:
![simplescreenrecorder-error](https://user-images.githubusercontent.com/79892286/218966744-32f3cf71-4485-4ca1-a177-544ca128b22b.svg)

**Comment by alvatip** [comment]
Thanks @Teatov , I will work on it in the following days !

**Comment by alvatip** [comment]
Hey @Teatov, I added the icons, all should works as expected now
