### ISSUE TITLE
[ICON] OnlyOffice 

### ISSUE THREAD

**Issue by Phiiniix** [alvatip/Nordzy-icon#115]
Application name: OnlyOffice Desktop Editors
Icon name if you know it: Don't Know ( asc-de-16, asc-de-24, asc-de-32, asc-de-48 asc-de-64, asc-de-128 and asc-de-256 ) 
Original icon image: https://avatars.githubusercontent.com/u/1426033?s=280&v=4
Use tray? Don't really know
Small description and/or a link to the official webpage: https://www.onlyoffice.com/fr/
Desktop File:

**Comment by alvatip** [comment]
@Phiiniix , thanks for reaching out!! :smile: 
There is already an icon for only office, so the correct name for the icon is missing.
To find it I should know what Linux distribution are you using ? And how did you installed only office (flatpak/flathub, snap/snapcraft, AppImage, ...) ? 
Once I have that information I should be able to fix it :wink:

**Comment by Phiiniix** [comment]
Hi ! 
I'm using Arch Linux and I installed OnlyOffice in the AUR.

**Comment by alvatip** [comment]
Thanks @Phiiniix ! I will have a look into it to see what is missing for the icon to work properly :wink:

**Comment by alvatip** [comment]
@Phiiniix, I brought some changes which should fix this issue. 
I tried it using a manjaro vm and it worked fine :wink:
If this is still not working with the last commit, feel free to reach to me here, I will leave this issue open for a few days
