### ISSUE TITLE
[ICON] Microsoft Edge

### ISSUE THREAD

**Issue by JamesSi22** [alvatip/Nordzy-icon#116]
Application name: Microsoft Edge
Icon name if you know it: 
Original icon image: https://icons8.com/icon/dGm9KIZPpukc/microsoft-edge
Use tray? Not positive
Small description and/or a link to the official webpage: Microsoft Edge Browser, https://www.microsoft.com/en-us/edge?exp=e00&form=MA13FJ

Thank you so much!

**Comment by alvatip** [comment]
I will work on it in the following days :wink:

**Comment by alvatip** [comment]
Hey @JamesSi22, I added the icon in the last commit, all should work fine :wink:

**Comment by JamesSi22** [comment]
Thank you so much! It looks great!
