### ISSUE TITLE
[BUG] VSCode

### ISSUE THREAD

**Issue by lodhi-abhishek** [alvatip/Nordzy-icon#117]
**VSCode Icon Doesn't work**
I figured out that in desktop of vscode. The Icon entry is updated
```diff
+Icon=vscode
-Icon=com.visualstudio.code
```
**To Fix**
- Rename the existing [com.visualstudio.code.svg](https://github.com/alvatip/Nordzy-icon/blob/main/src/apps/scalable/com.visualstudio.code.svg) to vscode.svg
-  Update the icon cache
 
**Desktop**
Linux Mint 21 Cinnamon

**Additional context**

**Comment by alvatip** [comment]
Hi @lodhi-abhishek 
Thanks for noticing and reporting :+1: 
I made the needed changes in the last commit so it should work properly now

**Comment by lodhi-abhishek** [comment]
Thanks @alvatip for Fix the issues.
