### ISSUE TITLE
[ICON] RaySession

### ISSUE THREAD

**Issue by dsheeler** [alvatip/Nordzy-icon#118]
Application name: RaySession
Icon name if you know it: raysession
Original icon image: ![raysession](https://user-images.githubusercontent.com/1632985/220587810-464d08c0-751a-4745-bb82-267fd90e5bdf.svg)
Use tray? It has an appindicator icon, but think it uses svg icon?
Small description and/or a link to the official webpage: [github site](https://github.com/Houston4444/RaySession)

**Comment by dsheeler** [comment]
I see the new icon generally, but the old one still shows up in the tray... 
![trayiconanddockiconnomatchtrayiconshouldbynordzytoo](https://user-images.githubusercontent.com/1632985/222641923-50105249-c2d6-433c-be81-3a831f299e0a.png)

**Comment by alvatip** [comment]
I tried a lot, but I can't find the name of the system tray icon and can't change it ... @Houston4444, sorry to bother you here, but maybe do you now how could I apply the icon theme to the tray icon ? Thanks a lot

**Comment by Houston4444** [comment]
It comes from the program itself, see https://github.com/Houston4444/RaySession/blob/c34969641959802059ccccd152e82de978467ff6/src/gui/main_window.py#L404 .

Maybe should I use the RaySession system icon instead.

**Comment by Houston4444** [comment]
I fixed this, in last commit systray icon is now taken from system icons if it exists.

https://github.com/Houston4444/RaySession/commit/8aa3eec0298dbd7098a0d6d4250ad1db60d000c9

**Comment by dsheeler** [comment]
@Houston4444, works for me 🥇

**Comment by alvatip** [comment]
Thanks a lot for your help @Houston4444 I really appreciate it :1st_place_medal:
