### ISSUE TITLE
[ICON]more new icons

### ISSUE THREAD

**Issue by 80luna80** [alvatip/Nordzy-icon#12]
Application name: pidgin, mysql-workbench, filezilla, rapidsvn
Use tray? no
Small description and/or a link to the official webpage:
https://www.pidgin.im/
https://www.mysql.com/it/products/workbench/
https://filezilla-project.org/
https://rapidsvn.org/

thanks a lot, very nice iconset

**Comment by alvatip** [comment]
Icons added :wink: 
I will create a new release in 2 weeks, meanwhile you can use the latest version by cloning the repo and using the installation script!
Preview:
![image](https://user-images.githubusercontent.com/84344248/152351054-36b33c6a-d4ec-4995-aa65-ae246feeb401.png)
![image](https://user-images.githubusercontent.com/84344248/152351133-e81b2d38-fcd1-4630-9495-223e969fc711.png)
![image](https://user-images.githubusercontent.com/84344248/152351242-0fe69143-0561-4e7d-b991-495e622ce380.png)
![image](https://user-images.githubusercontent.com/84344248/152351376-cd80413e-becd-4fbc-aa3d-b48793e61b82.png)

**Comment by 80luna80** [comment]
Thanks a lot, very beautifull!

Il Gio 3 Feb 2022, 14:26 alvatip ***@***.***> ha scritto:

**Comment by 80luna80** [comment]
I forgot geany
https://www.geany.org/

If and when you can. Thanks



Il giorno gio 3 feb 2022 alle ore 17:57 Diana Candolfi ***@***.***>
ha scritto:

**Comment by alvatip** [comment]
Sure, 
I don't have much idea for the design of this icon for now… Here is what I did for now
![image](https://user-images.githubusercontent.com/84344248/152702064-221e01f1-02ec-4dea-9158-0d4687779e03.png)
Any thought? 
Maybe I could create a more faithful icon to the original one? Something that could look more like this ? 
![image](https://user-images.githubusercontent.com/84344248/152702133-2643c7c7-0b40-456d-b5a4-d57a166e28ed.png)

**Comment by 80luna80** [comment]
for me are both very beautiful, I cannot choose which I really prefer,
maybe the first...maybe

Il giorno dom 6 feb 2022 alle ore 22:30 alvatip ***@***.***>
ha scritto:

**Comment by alvatip** [comment]
Let's go for the first one ! I will perform adjustments later if needed :wink:

**Comment by 80luna80** [comment]
Can you provide an icon for google chat too?

If and when you can, many thanks.

**Comment by alvatip** [comment]
I created the icon, however, I don't know the name that I should use for this icon (currently set to "google-chat")
Do you know the name ? Or do you have some more information like the GitHub project or where the icon is being display on your installation or anything else ? 

Thanks

**Comment by 80luna80** [comment]
First off all many thanks.
I checked in the settings of xfce4 panel (where I have the launcher for
google chat) and the file is so













*[Desktop Entry]Version=1.0Terminal=falseType=ApplicationName=Google
ChatExec=/opt/google/chrome/google-chrome --profile-directory=Default
--app-id=mdpkiolbdkhdjpekfbkbmhigcaggjagiIcon=chrome-mdpkiolbdkhdjpekfbkbmhigcaggjagi-DefaultStartupWMClass=crx_mdpkiolbdkhdjpekfbkbmhigcaggjagiX-XFCE-Source=file:///home/diana/.local/share/applications/chrome-mdpkiolbdkhdjpekfbkbmhigcaggjagi-Default.desktopComment=Path=StartupNotify=false*

Unfortunately I don't think that the Icon is the same for everyone.
I don't know how to find more info, I'm sorry.
Maybe, if you don't find somethings usefull for everyone, can you send me
the icon? I change it manually in the panel.
I like very much your icon theme, the best!
I'm sorry, if you lose time for this icon and is not possible to use it for
everyone






Il giorno mar 1 nov 2022 alle ore 16:10 alvatip ***@***.***>
ha scritto:

**Comment by MolassesLover** [comment]
It's no problem but please use Markdown when posting things such as `.desktop` files, it makes everything a lot easier to read.

**Comment by alvatip** [comment]
This is what I was looking for, thanks @80luna80 !
I will make the needed changes tomorrow.

**Comment by alvatip** [comment]
@80luna80, changes are made so it should display properly, could you maybe try it with the last commit ? (so using the install.sh script, I have not updated yet the files in the releases and on pling.com) 
Thanks!

**Comment by 80luna80** [comment]
It's works perfectly!

Thanks a lot lot lot!

Il giorno ven 4 nov 2022 alle ore 12:56 alvatip ***@***.***>
ha scritto:

**Comment by alvatip** [comment]
Thanks for your return!
