### ISSUE TITLE
[ICON] XChat

### ISSUE THREAD

**Issue by dsheeler** [alvatip/Nordzy-icon#120]
Application name: XChat
Icon name if you know it: xchat 
Original icon image: 
![xchat](https://user-images.githubusercontent.com/1632985/220690230-02156342-eae1-420d-808a-491f52ab7bf8.svg)

Use tray? Yes, but I'm not sure it uses a separate icon?
Small description and/or a link to the official webpage: http://xchat.org/

**Comment by alvatip** [comment]
@dsheeler , I added the icon for xchat. I do not know if the tray icon will work, I tried testing it but I cannot find a way to install the application, I always encounter several errors during the installation process :smiling_face_with_tear: 
Does the tray icon on your system looks like theses ? 
![image](https://user-images.githubusercontent.com/84344248/222794232-8d50353f-b2a4-4fdf-af6c-d2421b6a63c9.png)
![image](https://user-images.githubusercontent.com/84344248/222794305-62bb41d3-64fa-447b-a3ca-83bd0206e90e.png)

**Comment by alvatip** [comment]
@dsheeler, 
I added the panel icon, so all should work properly
