### ISSUE TITLE
[ICON] Ario

### ISSUE THREAD

**Issue by dsheeler** [alvatip/Nordzy-icon#121]
Application name: Ario
Icon name if you know it: ario
Original icon image: 
![ario](https://user-images.githubusercontent.com/1632985/220693029-8a0c50ca-b5e5-4119-b40e-0efd14fbd7e2.svg)

Use tray? No
Small description and/or a link to the official webpage: https://ario-player.sourceforge.net/index.php

**Comment by alvatip** [comment]
@dsheeler, thanks, I will work on these in the following days :wink:

**Comment by dsheeler** [comment]
Can't wait!

**Comment by dsheeler** [comment]
@alvatip, this one I really like.  Thank you! My regular dash is full of Nordzy icons now.  Love it!!!

**Comment by alvatip** [comment]
@dsheeler, you are more than welcome :wink:
