### ISSUE TITLE
[ICON] Element

### ISSUE THREAD

**Issue by dsheeler** [alvatip/Nordzy-icon#123]
Application name: Element
Icon name if you know it: element
Original icon image: 
![io element Element](https://user-images.githubusercontent.com/1632985/222869517-60997830-c18c-4495-9588-66de3efaa9db.svg)

Use tray? No
Small description and/or a link to the official webpage: Matrix messenger application: https://element.io/

**Comment by alvatip** [comment]
@dsheeler, I will do this one in the following days :wink:

**Comment by dsheeler** [comment]
I was incorrect, this one does use systemtray

**Comment by alvatip** [comment]
Icon + systemtray is added
