### ISSUE TITLE
[ICON] Qalculate!

### ISSUE THREAD

**Issue by Teatov** [alvatip/Nordzy-icon#125]
Application name: Qalculate! (Qt and GTK versions)
Icon name if you know it: io.github.Qalculate.qalculate-qt, qalculate-qt, qalculate-gtk, qalculate
Original icon image: 
![qalculate-qt](https://user-images.githubusercontent.com/79892286/225643159-d514adc5-ae9b-4d55-a951-6c8800bc6b0e.svg)
Use tray? no

Small description and/or a link to the official webpage: Multi-purpose cross-platform desktop calculator. http://qalculate.github.io/

**Comment by alvatip** [comment]
Icon added :wink:
