### ISSUE TITLE
[ICON] Docker Desktop

### ISSUE THREAD

**Issue by Teatov** [alvatip/Nordzy-icon#126]
Application name: 
Icon name if you know it: docker-desktop
Original icon image: 
![icon original](https://user-images.githubusercontent.com/79892286/225644557-6ac53466-afbd-481d-bca9-e08763ff4076.png)
Use tray? yes, but the tray icon is animated, and I think it's embedded in the binaries.
Small description and/or a link to the official webpage: application for the building and sharing of containerized applications and microservices. https://www.docker.com/products/docker-desktop/

**Comment by alvatip** [comment]
This one is also added in the last commit. 
Systray is likely embedded in binaries, I couldn't find it nor useful information about it, I will still have a look later, maybe I missed something
