### ISSUE TITLE
[ICON] Soundux

### ISSUE THREAD

**Issue by Teatov** [alvatip/Nordzy-icon#127]
Application name: Soundux
Icon name if you know it: soundux, io.github.Soundux
Original icon image: 
![soundux](https://user-images.githubusercontent.com/79892286/225647912-5b33ffb2-41c3-4750-bc7e-2e8be10ca751.png)
Use tray? yes
Small description and/or a link to the official webpage: a cross-platform soundboard. https://soundux.rocks/

**Comment by alvatip** [comment]
I added the icon, 
I also had a look for the systray icon but couldn't find it,
I believe that it will use the app icon or that this is hardcoded in the app :stuck_out_tongue:
