### ISSUE TITLE
[ICON] Mullvad Browser

### ISSUE THREAD

**Issue by saltrafael** [alvatip/Nordzy-icon#129]
Application name: Mullvad Browser
Small description and/or a link to the official webpage: https://github.com/mullvad/mullvad-browser/tree/mullvad-browser-102.9.0esr-12.0-2

![default128](https://user-images.githubusercontent.com/76502841/229631598-60f66f9d-39f3-4b71-81e3-2b560daefac2.png)

**Comment by alvatip** [comment]
Hey @saltrafael,
I added the icon in the last commit.
I believe it should work fine, however I am not a 100% sure... Could you confirm it's proper functioning ? I broke my VM so I did not had the opportunity to verify it yet

**Comment by saltrafael** [comment]
@alvatip it looks perfect, thank you!!

**Comment by alvatip** [comment]
You are very welcome
