### ISSUE TITLE
[ICON] The Shotcut icon feels out of place 

### ISSUE THREAD

**Issue by MolassesLover** [alvatip/Nordzy-icon#133]
Hi, thanks for adding the Shotcut icon! I'm happy to have it, it looks much better than the original. Although, the flat rendering feels really out of place. Most of the icons I use have a gradient, as they aren't depicting a rough material. I'm assuming the icon is based on a film strip, so it would make more sense if it were shiny, as well.

I don't know how I feel about the gaps between the strips, either, but I don't think they're what really makes the icon feel out of place to me.

**Comment by alvatip** [comment]
Hi, 
Thanks for letting me know! 
I brought some modification to the icon to give it a better look, 
Let me know what your thought are

![shotcut](https://user-images.githubusercontent.com/84344248/235627209-956d7a38-d8f8-4be7-b309-4718cb6b464d.svg)

**Comment by MolassesLover** [comment]
That looks much better, thank you so much!
