### ISSUE TITLE
[ICON] Vieb Browser

### ISSUE THREAD

**Issue by saltrafael** [alvatip/Nordzy-icon#136]
Application name: Vieb Browser
Small description and/or a link to the official webpage: https://github.com/Jelmerro/Vieb

![image](https://github.com/alvatip/Nordzy-icon/assets/76502841/1999c8e8-aceb-49a3-8e9c-a0727b789457)

**Comment by alvatip** [comment]
I will do that tomorrow 😉

**Comment by alvatip** [comment]
I added the icon in the last commit, it should work properly :wink:
