### ISSUE TITLE
[ICON] Flatpak Minecraft

### ISSUE THREAD

**Issue by albertescanes** [alvatip/Nordzy-icon#137]
Application name: Minecraft
Icon name if you know it: com.mojang.Minecraft
Small description and/or a link to the official webpage:

Hello,

I noticed there is an icon for Minecraft (which looks great!!!). However, it does not apply to the flatpak version. Would it be possible to add it?

Thank you for your work !!

**Comment by alvatip** [comment]
Hey, 
I fixed this in the last commit :wink:
