### ISSUE TITLE
[ICON] melonDS

### ISSUE THREAD

**Issue by albertescanes** [alvatip/Nordzy-icon#139]
Application name: melonDS
Icon name if you know it: net.kuribo64.melonDS (This is the flatpak icon, I don't know where else the icon is used, I don't see that the official binary uses it)
Original icon image: https://github.com/melonDS-emu/melonDS/blob/master/res/icon/melon_256x256.png
Use tray? Pretty sure it doesn't.
Small description and/or a link to the official webpage:
Hello,
I'm requesting an icon for melonDS.
melonDS is a DS emulator.
https://melonds.kuribo64.net/
https://github.com/melonDS-emu/melonDS

Thank you for your work!

**Comment by alvatip** [comment]
I added the icon in the last commit, it should work properly :wink: 
If not, don't hesitate to leave a comment and I will fix it

**Comment by albertescanes** [comment]
Thank you!!
