### ISSUE TITLE
[ICON] Cinnamon settings icons

### ISSUE THREAD

**Issue by mseveritt** [alvatip/Nordzy-icon#14]
Application name: Cinnamon 5.2.7 Settings
Application: cinnamon-settings (specific setting) (e.g. (specific setting)=hotcorners)
Icon name: cs-*, e.g. cs-overview
Use tray? No
Small description and/or a link to the official webpage:
Icons for Cinnamon settings are not in the very nice Nordzy design.
Most of them seem to be from Numix, some are symbolic:
![grafik](https://user-images.githubusercontent.com/61334079/156394112-6dcbc8c9-3cb6-4394-8bc6-3839fc88d34a.png)

**Comment by alvatip** [comment]
I will work on it!
Thanks for reporting this 😉

**Comment by mseveritt** [comment]
Thanks for your feedback. I think most of the icons are already there, only the links are needed.

**Comment by mseveritt** [comment]
Suggested mapping for linking existing icon to new one 
(list is WIP and contains other icons as well which are relevant for Linux Mint):
software-update.svg -> mintupdate.svg
org.xfce.settings.appearance.svg -> cs-themes.svg
lightdm-settings.svg -> lightdm-gtk-greeter-settings.svg
system-software-install.svg -> mintsources.svg
system-software-install.svg -> synaptic.svg

**Comment by mseveritt** [comment]
I am about to create a PR for this and some minor changes.

**Comment by alvatip** [comment]
Thanks!

**Comment by mseveritt** [comment]
No problem, I am happy to learn and contribute. There are some more to come.

**Comment by mseveritt** [comment]
I think I am finished with mapping existing icons to missing ones (new PR is created). The only few ones left are mentioned above. They may have to be created as I did not find a match.

**Comment by alvatip** [comment]
Great, thanks for your help!
I will modify some of them, especially the one for which i think I should create a new icon: 

- [ ] bulky
- [ ] hypnotix
- [ ] celluloid
- [ ] pdfarranger
- [ ] cs-background
- [ ] cs-tablet

**Comment by alvatip** [comment]
All should be good now, 
I will test it a little bit on cinnamon during the week, and bring some changes if needed :small_airplane:

**Comment by alvatip** [comment]
e0fb38449bddc9d8bf630ac1e14b9764f44debd8

**Comment by mseveritt** [comment]
Thanks a lot!
Maybe it is just for me, but somehow cs-tablet.svg does not work. The rest works like a charm.
![grafik](https://user-images.githubusercontent.com/61334079/156920310-6531baf0-a1b3-49f1-8006-05690777a8aa.png)
![grafik](https://user-images.githubusercontent.com/61334079/156920370-0ee87a8f-3ab0-40c2-8943-ad691c216add.png)

**Comment by mseveritt** [comment]
I got it: The icon for cs-tablet.svg needs to be tablet.svg in devices in order to work. I also updated drive-removable-media.svg in devices which impacts volman in XFCE. PR is created.

**Comment by mseveritt** [comment]
On second thought, this was not a good idea for the consistency of devices-icons. Sorry. 
All that is necessary is your cs-tablet.svg and org.xfce.volman.svg from apps present in devices and their devices-links removed.
Revised PR is on its way.

**Comment by mseveritt** [comment]
Done.
