### ISSUE TITLE
[ICON] Openshot 

### ISSUE THREAD

**Issue by 80luna80** [alvatip/Nordzy-icon#140]
Application name: Openshot
Icon name if you know it: openshot-qt
Original icon image: https://cdn.openshot.org/static/img/logos/logo.png
Use tray? No
Small description and/or a link to the official webpage:
Video editing software
https://www.openshot.org/
----------
Thank you very much, if you can create this icon!! I appreciate a lot your work! Great! The best icon set ever!

**Comment by alvatip** [comment]
I added the icon in the last commit, 
If it does not work properly, just reopen this issue so i can fix it :wink:

**Comment by 80luna80** [comment]
thanks a lot, it works perfectly!
