### ISSUE TITLE
[ICON] wezterm

### ISSUE THREAD

**Issue by ttntm** [alvatip/Nordzy-icon#141]
Application name: wezterm

Icon name if you know it: org.wezfurlong.wezterm

Original icon image: https://github.com/wez/wezterm/commit/5a60bddba7048aba27dcd1bb3b3ed275b0a681e7

Use tray? no

Small description and/or a link to the official webpage: https://github.com/wez/wezterm & https://wezfurlong.org/wezterm/

![org wezfurlong wezterm](https://github.com/alvatip/Nordzy-icon/assets/41571384/1400cb96-ff0f-4f1c-b986-2f96823f86dc)

**Comment by alvatip** [comment]
I added the icon in the last commit!
Feel free to reopen the issue if it does not work properly and I will fix it :wink:

**Comment by ttntm** [comment]
Love how it turned out, thanks!
