### ISSUE TITLE
[ICON] foot

### ISSUE THREAD

**Issue by e-tho** [alvatip/Nordzy-icon#142]
Application name: foot

Icon name if you know it: `foot`

Original icon image: https://codeberg.org/dnkl/foot/media/branch/master/icons/hicolor/scalable/apps/foot.svg

Use tray? No

Small description and/or a link to the official webpage: "The fast, lightweight and minimalistic Wayland terminal emulator." 
https://codeberg.org/dnkl/foot

**Comment by alvatip** [comment]
I added the icon in the last commit. It shoudl work properly! 
If not, please reopen this issue so I can fix it :wink:
