### ISSUE TITLE
[ICON] Insomnia

### ISSUE THREAD

**Issue by e-tho** [alvatip/Nordzy-icon#143]
Application name: Insomnia
Icon name if you know it: `insomnia`
Original icon image: https://insomnia.rest/images/insomnia-logo.svg
Use tray? No
Small description and/or a link to the official webpage: "Insomnia is an open-source, cross-platform API client for GraphQL, REST, WebSockets and gRPC."
https://insomnia.rest/ & https://github.com/Kong/insomnia

**Comment by alvatip** [comment]
I added the icon in the last commit. It shoudl work properly! 
If not, please reopen this issue so I can fix it :wink:
