### ISSUE TITLE
[ICON] Cider

### ISSUE THREAD

**Issue by e-tho** [alvatip/Nordzy-icon#144]
Application name: Cider
Icon name if you know it: `cider`
Original icon image: https://raw.githubusercontent.com/ciderapp/Cider/main/src/renderer/assets/c1-c2.png
Use tray? Yes
Small description and/or a link to the official webpage: "A new cross-platform Apple Music experience based on Electron and Vue.js written from scratch with performance & visuals in mind." https://github.com/ciderapp/Cider / https://github.com/ciderapp/Cider-2 & https://cider.sh/

**Comment by alvatip** [comment]
@e-tho, 
The cider icon already exists in the icon pack, if it does not display properly, could you please provide the linux distro you're using and the way you installed it ? (repo, flatpak or snap? or other, such as appimage...)

Thanks

**Comment by e-tho** [comment]
@alvatip 
All good, I wasn't up to date with the repo, I was using the release version of the AUR package. I didn't see any requests in the issues for this icon, so I assumed it wasn't there. 

Thanks for this great theme
