### ISSUE TITLE
User submitted icons?

### ISSUE THREAD

**Issue by Readf0x** [alvatip/Nordzy-icon#145]
Sorry for asking about this in a github issue, but I didn't see an any form of contact on your github account.

I went ahead and made a few icons because applications I use frequently weren't supported. I'll upload them here but I don't know if they're good enough to be included :P

![youtube-music-desktop](https://github.com/alvatip/Nordzy-icon/assets/57838054/e57188c5-4836-4f4d-80b1-5006d69a260a)
![youtube](https://github.com/alvatip/Nordzy-icon/assets/57838054/b98a09dc-3c75-4842-a159-71251d3b8bf8)
![prism-launcher](https://github.com/alvatip/Nordzy-icon/assets/57838054/c61dc6eb-03a5-4ffa-b42a-9527a7cf4efb)

**Comment by Readf0x** [comment]
forgot to mention, the applications here are ytmdesktop ([app.ytmdesktop.ytmdesktop](https://flathub.org/apps/app.ytmdesktop.ytmdesktop)) a generic youtube icon for pwas, and prism launcher ([org.prismlauncher.PrismLauncher](https://flathub.org/apps/org.prismlauncher.PrismLauncher))

**Comment by Readf0x** [comment]
I have now also made icons for the pop shop and notable!
![notable](https://github.com/alvatip/Nordzy-icon/assets/57838054/d0779f29-38d2-4ffb-9fad-6d3095e45780)
![pop-shop](https://github.com/alvatip/Nordzy-icon/assets/57838054/ac0cc88c-43c7-45ab-a620-22ab79d47c45)
took me forever to find the pop shop's icon name, but it's apparently based on the app store from elementary.

**Comment by alvatip** [comment]
Hey @Readf0x, 
Sure, I will take a look and include them in the pack :wink: 
Thanks for contributing !!

**Comment by alvatip** [comment]
Just a few questions :stuck_out_tongue: 
- Is the very first icon Cider ? (red play logo, round)
- Do you have the name for notable and the pop shop ? Otherwise, I can install them in a vm and find the icon name, but since you are using them it might be easier if you already have them :smile: 

edit: to find most of the icon names easily, I run these two commands in my terminal
`cd /usr/share/applications/`
`grep -e "^Icon=.*nameoftheapp.* *` where nameofthe app is the name (or part of the name) of the application. e.g. for Firefox, I would try 'firefox' or 'irefox' (in case the first letter is uppercase)
![image](https://github.com/alvatip/Nordzy-icon/assets/84344248/503457ca-38ac-435c-95a8-e5aa21eccfed)

**Comment by Readf0x** [comment]
OMG thank you, I didn't know grep could be used to search inside files! I'll be back at my pc in a few minutes, so I'll figure out what what it's called then. I would like to know how I should submit icons in the future though?

**Comment by alvatip** [comment]
Thanks, I added them to the theme and will commit it shortly :wink: 

To submit icon, the easiest way is to create a pull request (see [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) page for more details on how to submit a pull request)

For the creation of icons, there are some blank templates in `tools/templates` and color palettes in `tools/palettes`that can help you. 

Once your icon is created, you name it and place it in `src/apps/scalable`. 

If the app as several possible names (ex: for Firefox, the app will use firefox (if installed through repo) or `org.mozilla.firefox` if installed through flatpak), you will need to create symbolic links in `links/apps/scalable` pointing to the icon in `src/apps/scalable`. 
So for Firefox which has at least 2 names, I will have an SVG icon named 'firefox.svg' in src/apps/scalable then I will create a symbolic link in links/apps/scalable named `org.mozilla.firefox.svg`

To create the symbolic link, I use the following command:
`cd src/apps/scalable`  (just 'cd' into the directory src/apps/scalable)
`ln -s firefox.svg ../../../links/apps/scalable/org.mozilla.firefox.svg` (create the symlink with other name used by the app)

I hope all is clear, if not don't hesitate to ask further question, or create a first pull request and if there are mistakes we can correct them :wink:

**Comment by Readf0x** [comment]
I'll be closing the issue now, since everything seems to have been resolved. Thanks for your time!
