### ISSUE TITLE
[BUG] Symbolic icons don't change color in qt apps

### ISSUE THREAD

**Issue by Readf0x** [alvatip/Nordzy-icon#146]
**Describe the bug**
Symbolic icons don't change color in some applications, mainly qt apps. This is because most symbolic icons use element styles to set the color to nord0. To fix, just change the color to currentColor, but don't use classes to change it to nord0 anyways, as this will prevent some applications from changing the icon color.

**To Reproduce**
Set qt icon theme to nordzy and open a qt application

**Expected behaviour**
Icons can change color.

**Screenshots**
![image](https://github.com/alvatip/Nordzy-icon/assets/57838054/c7808959-662c-4d36-b8e3-d091ee9754d3)
![image](https://github.com/alvatip/Nordzy-icon/assets/57838054/9a3b2d8b-fd7c-4b8c-9c32-43390b0de10d)
![image](https://github.com/alvatip/Nordzy-icon/assets/57838054/4f5ed5a5-c808-4558-93de-ea5722578544)

**Desktop**
I'm using Gnome 42 on Pop!_OS (debian), but this does affect all distributions.

**Comment by alvatip** [comment]
Thanks for noticing, I will take a look at that

**Comment by alvatip** [comment]
Hey @Readf0x, 
I was wondering which theme are you using ? 
Don't ask me why, that was some years ago, and I was less experienced, but I encountered an issue and I chose not to use currentColor, instead I am changing the color when installing a theme. 
So symbolic icons in Nordzy are set to Nord0(dark) and symbolic icon in Nordzy-dark are set to Nord6 (light)

PS: Yes, I know that the name are counter intuitive, when I named them I thought Nordzy for overall light theme (=> so dark symbolic icons) and Nordzy-dark for overall dark theme (=> so light symbolic icons) :stuck_out_tongue:

**Comment by Readf0x** [comment]
I'm using the [Nordic theme](https://www.gnome-look.org/p/1267246/).

I didn't know there was a Nordzy dark, actually... That would've saved me so much time... 🤦

**Comment by Readf0x** [comment]
Upon further inspection, this affects GTK apps as well.

![image](https://github.com/alvatip/Nordzy-icon/assets/57838054/3aac0d09-d508-4fe1-bfc3-819f4c275bdc)

I would assume that when text is using the selected color, so should symbolic icons. However I'm no expert on GTK, so it's entirely possible I'm wrong.

**Comment by alvatip** [comment]
Damn!
Thanks for reporting it, I will try using currentColor, hoping it solve the issue :stuck_out_tongue:

**Comment by alvatip** [comment]
I believe I found the fix, I don't think I will have time to do it today nor this weekend, so it will most likely be on Monday

**Comment by alvatip** [comment]
@Readf0x ,
I brought some changes to the icons, 
![Screenshot_20230719_134849](https://github.com/alvatip/Nordzy-icon/assets/84344248/3de7fa0a-873a-48f6-8f9e-2e02c44f5027)
Here is what I see in kvantum, using Nordic theme, maybe you can confirm that changes in the last commit were indeed successful ? 
Thanks
