### ISSUE TITLE
[BUG] Symbolic mime types don't get changed in dark mode.

### ISSUE THREAD

**Issue by Readf0x** [alvatip/Nordzy-icon#148]
**Describe the bug**
Symbolic mime types don't get changed from nord0 to nord16 when using the install script. The latest release is also affected by this issue.

**To Reproduce**
Run the install script with the color set to dark.

**Expected behaviour**
From what I can see in the install script, the mime type symbols that don't have a specific color are supposed to change from nord0 to nord16.

**Screenshots**
![image](https://github.com/alvatip/Nordzy-icon/assets/57838054/5ca9aff3-a9d7-40d1-83ac-ee2615035196)

**Desktop**
Gnome

**Comment by alvatip** [comment]
Thanks for reporting, I will make some changes there too :stuck_out_tongue:
