### ISSUE TITLE
[ICON] More new icons

### ISSUE THREAD

**Issue by vanillamatcha** [alvatip/Nordzy-icon#15]
Application name: AppEditor, BleachBit, Connections, Fragments, Foliate, Pomodoro, Telegram, VS Code, and Weather 

Use tray? No

Small description and/or a link to the official webpage:
https://appcenter.elementary.io/com.github.donadigo.appeditor/
https://www.bleachbit.org/
https://gitlab.gnome.org/GNOME/connections
https://apps.gnome.org/app/de.haeckerfelix.Fragments/
https://johnfactotum.github.io/foliate/
https://gnomepomodoro.org/
https://telegram.org/
https://code.visualstudio.com/
https://gitlab.gnome.org/GNOME/gnome-weather

And a little advice, what if the tray icon is changed as follows?
![image](https://user-images.githubusercontent.com/36553432/156476728-a4d2d80d-dcc8-44dd-913f-c933c6cba3da.png)

Then I'm just trying to add a new folder theme variant, namely Dracula, to my personal storage :)
![image](https://user-images.githubusercontent.com/36553432/156483552-97254518-b659-47ed-905a-99bd90dbce06.png)

Sorry too many requests, thanks a lot for such a great work.

**Comment by vanillamatcha** [comment]
Hi, I just created the icon for vscode and slightly changed the color for the calculator icon, sticking with the nord color scheme.
hope it helps a little :)

![visual-studio-code](https://user-images.githubusercontent.com/36553432/156502552-68e6ac5a-34d5-4a97-9c76-d4dde2069f3c.svg) ![calc](https://user-images.githubusercontent.com/36553432/156502583-f4c417c7-c0d7-4293-bdf1-7dfab4bd0896.svg)

**Comment by vanillamatcha** [comment]
Hi, I just created the icon for telegram, vscode and slightly changed the color for the calculator icon, sticking with the nord color scheme. Hope it helps a little :)

![telegram](https://user-images.githubusercontent.com/36553432/156504620-1d5187ae-d7b0-4b18-87e6-7794d10add4e.svg) ![visual-studio-code](https://user-images.githubusercontent.com/36553432/156502552-68e6ac5a-34d5-4a97-9c76-d4dde2069f3c.svg) ![calc](https://user-images.githubusercontent.com/36553432/156504935-63b731e0-68a6-46f9-9f71-f4307672b411.svg)

**Comment by vanillamatcha** [comment]
Hello, I just created the icons for telegram and vscode, and changed the color a bit for the calculator, but still using the nord color scheme.

![telegram](https://user-images.githubusercontent.com/36553432/156509259-26be0c79-a091-481f-8970-76d6d933e733.svg) ![visual-studio-code](https://user-images.githubusercontent.com/36553432/156509237-24108742-4a5d-44df-9de6-e46ea35dd497.svg) ![calc](https://user-images.githubusercontent.com/36553432/156509268-e5f599bc-e96a-4faf-b0ed-f03ee5ce5229.svg)

Hope it helps a little :)

**Comment by vanillamatcha** [comment]
Hello, I just created the icons for telegram, pomodoro, and vscode.

![telegram](https://user-images.githubusercontent.com/36553432/156509259-26be0c79-a091-481f-8970-76d6d933e733.svg) ![pomidor](https://user-images.githubusercontent.com/36553432/156550754-78310660-017a-459c-965e-b68bbf73405a.svg) ![visual-studio-code](https://user-images.githubusercontent.com/36553432/156509237-24108742-4a5d-44df-9de6-e46ea35dd497.svg) 

And slightly improve in calculator icon and fedora media, but still using the nord color scheme.
![calc](https://user-images.githubusercontent.com/36553432/156509268-e5f599bc-e96a-4faf-b0ed-f03ee5ce5229.svg) ![fedora-media-writer](https://user-images.githubusercontent.com/36553432/156537728-a78253ff-f33e-4a79-a8ab-7e7d7ac4610f.svg)


Hope it helps a little :)

**Comment by alvatip** [comment]
Thanks for reporting, this is how the project can progress :wink: I will work on this very soon

**Comment by vanillamatcha** [comment]
Thanks for your feedback. And I'm trying to create icons for telegram and vscode,
![telegram](https://user-images.githubusercontent.com/36553432/156706924-956399c6-0168-4205-a0b5-dec1bdc8bb29.svg) ![visual-studio-code](https://user-images.githubusercontent.com/36553432/156706931-c3dfb8a8-9d4e-4214-b1d1-aec884528ee9.svg)

as well as improving the calculator and media fedora icons. But still using the nord color scheme.
![calc](https://user-images.githubusercontent.com/36553432/156706960-148f8d9e-4b7c-4ef4-b22f-aeb9ce9dee00.svg) ![fedora-media-writer](https://user-images.githubusercontent.com/36553432/156706982-16125228-23d8-4b61-af3b-4e99bc610ca8.svg)

Hope it helps a little.

**Comment by vanillamatcha** [comment]
Thanks for your feedback. And I'm trying to create icons for telegram and vscode,
![telegram](https://user-images.githubusercontent.com/36553432/156706924-956399c6-0168-4205-a0b5-dec1bdc8bb29.svg) ![visual-studio-code](https://user-images.githubusercontent.com/36553432/156706931-c3dfb8a8-9d4e-4214-b1d1-aec884528ee9.svg)

as well as improving the calculator and fedora media icons. But still using the nord color scheme.
![calc](https://user-images.githubusercontent.com/36553432/156706960-148f8d9e-4b7c-4ef4-b22f-aeb9ce9dee00.svg) ![fedora-media-writer](https://user-images.githubusercontent.com/36553432/156706982-16125228-23d8-4b61-af3b-4e99bc610ca8.svg)

Hope it helps a little.

**Comment by alvatip** [comment]
Progress: 

- [ ] Telegram
- [ ] Visual studio
- [ ] Pomodoro
- [ ] Weather
- [ ] Bleachbit
- [ ] Appeditor
- [ ] Connections
- [ ] Fragments
- [ ] Foliate

**Comment by vanillamatcha** [comment]
dude, thanks for making the icon. really like this icon :D

**Comment by alvatip** [comment]
You are very welcome :wink:
