### ISSUE TITLE
[BUG] Two error messages when pulling updates

### ISSUE THREAD

**Issue by jkemp814** [alvatip/Nordzy-icon#151]
**Describe the bug**

Receiving two error messages while pulling updates

**To Reproduce**
Steps to reproduce the behaviour:

Execute 'git pull'

**Expected behaviour**

Should complete without errors listed below

**Desktop**

Fedora Linux 38 Silverblue

**Additional context**

./install.sh
 _   _               _           
| \ | | ___  _ __ __| |_____   _ 
|  \| |/ _ \| '__/ _` |_  / | | |
| |\  | (_) | | | (_| |/ /| |_| |
|_| \_|\___/|_|  \__,_/___|\__, |
                           |___/ 

Installing '/var/home/james/.local/share/icons/Nordzy'...
gtk-update-icon-cache: Cache file created successfully.
Installing '/var/home/james/.local/share/icons/Nordzy-dark'...
sed: can't read /var/home/james/.local/share/icons/Nordzy-dark/actions/32/dialog-selectors.svg: No such file or directory
sed: can't read /var/home/james/.local/share/icons/Nordzy-dark/actions/symbolic/dialog-selectors.svg: No such file or directory
gtk-update-icon-cache: Cache file created successfully.

**Comment by HFR1994** [comment]
+1 can confirmed this is still and issue, maybe got erased?

**Comment by D3vil0p3r** [comment]
+1

**Comment by D3vil0p3r** [comment]
+1 @alvatip

**Comment by distor-sil3nt** [comment]
+1 @alvatip I also get the error messages when installing the icons.

**Comment by alvatip** [comment]
@jkemp814 @HFR1994 @D3vil0p3r @distor-sil3nt 
Thank you for reporting and sorry for the delay of my answer, I got really busy the past 2 month at work so did not had the time to work on my theme, 
I will work on this issue next week !! :wink:

**Comment by alvatip** [comment]
Found the issue, it should be fixed with my last commit 😄

**Comment by distor-sil3nt** [comment]
I can verify that the errors don't occur anymore after your latest commit. :+1: Thx for the fix!

**Comment by jkemp814** [comment]
Good job. Works great.
