### ISSUE TITLE
[ICON] Black Box Terminal icon Request

### ISSUE THREAD

**Issue by OulipianSummer** [alvatip/Nordzy-icon#152]
Application name: Black Box
Icon name if you know it: com.raggesilver.Blackbox.svg
Original icon image: https://gitlab.gnome.org/uploads/-/system/project/avatar/20397/com.raggesilver.BlackBox.png?width=64
Use tray? No
Small description and/or a link to the official webpage: Black Box is a simple but elegant looking GTK terminal that can use Tilix themes. The project is hosted on [gitlab](https://gitlab.gnome.org/raggesilver/blackbox).

**Comment by alvatip** [comment]
Thanks, 
I will work on it this week :wink:
