### ISSUE TITLE
[Request] New Release or instructions on generating release files

### ISSUE THREAD

**Issue by rharmonson** [alvatip/Nordzy-icon#156]
**Is your feature request related to a problem? Please describe.**
Not reporting a problem, but I am seeking a new release or guidance. Your last release files are from 2021.

**Describe the solution you'd like**
Either a new release or instructions on how to generate the release files after cloning your repository.

**Describe alternatives you've considered**
Use the old release.

**Additional context**
I previously packaged Nordzy-icon using the release 1.8.5 files for use on a debian bullseye based spin. I am working on a new release based on debian bookworm and would like to include all of your updates after the 1.8.5 release.

Love your aesthetics and please continue maintaining both the Nordzy icons and cursors. They are beautiful.

Thank you!

**Comment by alvatip** [comment]
I created release 1.8.6 which should fix this 😉 
To create theses release file, I first install all the themes `./install.sh --total` on my computer
Then run the following script (note, some path are hardocded eg: project is located in $HOME/GitHub/Nordzy-icon) I planned to adapt it and just include it in the "tools" folder then got lost into work 😆 
```
#!/bin/bash
# helps create archives .tar.gz of github icons project to the right place.

project="Nordzy-icon"

# If project exist in my github folder
# if [ -d $HOME/GitHub/${project}/archives/ ]
if [ -d $HOME/GitHub/${project}/ ]
then
	# Delete existing archives
	# rm -rv $HOME/GitHub/${project}/archives/*
	cd $HOME/.local/share/icons/
	for icon in Nordzy*
	do
		# Create new one
		if [[ ${icon} = *-dark ]]
		then
			light_icon=${icon%-dark}
			rm -r ${icon}/animations*
		    rm -r ${icon}/categories/32
		    rm -r ${icon}/emblems/16
		    rm -r ${icon}/emblems/22
		    rm -r ${icon}/emblems/24
		    rm -r ${icon}/mimes/16
		    rm -r ${icon}/mimes/22
		    rm -r ${icon}/mimes/scalable
		    rm -r ${icon}/apps/scalable
		    rm -r ${icon}/devices/scalable
		    rm -r ${icon}/places/scalable
		    rm -r ${icon}/status/32
		    rm -r ${icon}/status/scalable

		    cp -r ${light_icon}/animations* 		${icon}/
		    cp -r ${light_icon}/categories/32 		${icon}/categories/
		    cp -r ${light_icon}/emblems/16 			${icon}/emblems/
		    cp -r ${light_icon}/emblems/22 			${icon}/emblems/
		    cp -r ${light_icon}/emblems/24 			${icon}/emblems/
		    cp -r ${light_icon}/mimes/16 			${icon}/mimes/
		    cp -r ${light_icon}/mimes/22 			${icon}/mimes/
		    cp -r ${light_icon}/mimes/scalable 		${icon}/mimes/
		    cp -r ${light_icon}/apps/scalable 		${icon}/apps/
		    cp -r ${light_icon}/devices/scalable 	${icon}/devices/
		    cp -r ${light_icon}/places/scalable 	${icon}/places/
		    cp -r ${light_icon}/status/32 			${icon}/status/
		    cp -r ${light_icon}/status/scalable 	${icon}/status/
		fi
		# cd ${icon}
		tar -zcf "${icon}.tar.gz" ${icon}
		# mv -v "${icon}.tar.gz" $HOME/GitHub/${project}/archives/
		mv -v "${icon}.tar.gz" $HOME/Downloads/
		# cd ../
	done
else
	echo "The specified directory does not exist"
fi
```

**Comment by rharmonson** [comment]
Perfect! Thank you. I will use the new release and capture your instructions and script for future use.

Very helpful and appreciate the speedy response.

> I planned to adapt it and just include it in the "tools" folder then got lost into work 😆

Happens to me all the time. So easy to get distracted by the next problem or feature.
