### ISSUE TITLE
Pixelated volume Icon

### ISSUE THREAD

**Issue by antwoor** [alvatip/Nordzy-icon#162]
**Describe the bug**
Volume icon is pixelated

**To Reproduce**
change volume

**Expected behaviour**
Nice sharp icon

**Screenshots**
![image](https://github.com/alvatip/Nordzy-icon/assets/140619787/90de2df5-c1c9-438b-9f14-25f0c88c5d9e)

**Desktop**
GNOME Shell 3.36.9

**Comment by alvatip** [comment]
Fixed in the last commit, 
Tested on Debian 10 - Gnome Shell 3.34
