### ISSUE TITLE
[FEATURE] Add aur package, symlink common icons

### ISSUE THREAD

**Issue by Curve** [alvatip/Nordzy-icon#19]
**Is your feature request related to a problem?** / **Describe the solution you'd like**
The reused icons should be symlinked to reduce the package size.

---

I have also created an AUR-Package for this icon theme which can be found here https://aur.archlinux.org/packages/nordzy-icon-theme-git ^^

**Comment by alvatip** [comment]
Thanks! Indeed, I should check for duplicates. More importantly, I am sure that not all the SVGs are optimized. I will do that very soon, It should not take too much time.

**Comment by alvatip** [comment]
All right, so, 
- I optimized all the icons
- Created symlinks for similar icons in the same tree (+-250 icons)
- Added the link to the AUR package in a banner in the README

If you have any others idea don't hesitate, otherwise I will close the issue :wink:

**Comment by Curve** [comment]
Very nice!
Thanks :D
