### ISSUE TITLE
[BUG] Missing wine icon and tray icons.

### ISSUE THREAD

**Issue by darkshram** [alvatip/Nordzy-icon#2]
**Describe the bug**
Missing wine icon for menu entry. Icon name is 'wine'.

**Screenshots**
The wine icon showed in Whisker menu is inherited from hicolor-icon-theme. Looks weird because (installed) Wine 6.0.1 has a broken icon.
![Captura de pantalla_2021-08-15_11-12-00](https://user-images.githubusercontent.com/10327500/129486059-6b2439b7-58d8-43b5-b438-47ec21350194.png)

Added some extra context to the screenshot for other icons in case is you find it useful. Liferea and Claws Mail are hardcoded icons (not too much to do with those).

DE: Xfce 4.16
OS: ALDOS 1.4
GTK Theme: Nordic
Icon Theme: Nordzy-red-dark
Cursor Theme: Nordzy-cursors

**Comment by alvatip** [comment]
Hi, 
I added the wine icon in my last commit ;)
I will look into the tray to update some of them that indeed looks strange

Have a nice day

**Comment by alvatip** [comment]
Icons updated: 
- [x] package update indicator, well if I modified the right one...
- [x] Nextcloud, it should look more like the original nextcloud tray icon
- [x] Firewall applet
- [x] Liferea

Icons not updated: 
- nm-applet. It is the icon from the theme, and I have no inspiration for a new one (if you have any suggestion ?)
- claws: hardcoded and not supported in [hardcode-tray](https://github.com/bilelmoussaoui/Hardcode-Tray). However, you can [report](https://github.com/bilelmoussaoui/Hardcode-Tray/issues) it if you wish ;)

For the liferea, you have to use [Hardcode-tray](https://github.com/bilelmoussaoui/Hardcode-Tray) to change it (liferea is supported). I didn't look into details how to use it, but once installed, i guess that running `sudo hardcode-tray --size 22 --theme Nordzy-dark` should do the trick (maybe the size argument isn't even needed). Don't forget that you need a conversion tool (cfr the README of Harcode-tray)

Tell me if all works.

**Comment by darkshram** [comment]
Everything written bellow was done before testing latest commit. Will test in a few minutes and fill a new comment later.

Icon name set used by [package-update-indicator](https://code.guido-berhoerster.org/projects/package-update-indicator/) and similar tools:

- system-software-update (application desktop files)
- software-update-available-symbolic (tray)
- software-update-urgent-symbolic (tray)
- system-software-update-symbolic (tray)

For nm-applet I may suggest trying something like the nm icon set from Fluent-dark (ethernet icon from this theme looks weird) or Vimix-dark icon themes. Tela and Layan icon themes has some nice icons (pretty much the same set as Fluent), but neither have a complete set. Vince Liuice icon themes are not very complete for desktops using tray (Cinnamon, MATE, Xfce, KDE) and usually recycles icon sets within his themes.

Fluent icon theme:
![fluent-icon-theme](https://user-images.githubusercontent.com/10327500/129636884-bcb353a2-4594-4055-b47e-d0eb7a69d87e.png)
Vimix icon-theme:
![vimix-icon theme](https://user-images.githubusercontent.com/10327500/129636916-76f07e9d-1128-49ae-9a32-69a332b540d9.png)

Numix has a very/most complete set of icons for status tray save for Adwaita/GNOME icon themes, but I don't think the design will fit with Nordzy style... but they could look good using the Nord pallete or just creating original ones based on the icon set.
Numix icon theme:
![numix-icon-theme](https://user-images.githubusercontent.com/10327500/129636899-424a9d10-8f8b-4704-9473-63c8eecada09.png)

I have most of Vince Liuce themes inheriting Numix/Numix-circle (without this, they have a lot of issues with any DE with the exception of GNOME). So, `Numix[circle|square]` could be a good start point.

/usr/share/icons/Numix/24/animations/nm-stage01-connecting01.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting02.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting03.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting04.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting05.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting06.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting07.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting08.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting09.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting10.svg
/usr/share/icons/Numix/24/animations/nm-stage01-connecting11.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting01.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting02.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting03.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting04.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting05.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting06.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting07.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting08.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting09.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting10.svg
/usr/share/icons/Numix/24/animations/nm-stage02-connecting11.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting01.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting02.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting03.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting04.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting05.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting06.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting07.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting08.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting09.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting10.svg
/usr/share/icons/Numix/24/animations/nm-stage03-connecting11.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting01.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting02.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting03.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting04.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting05.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting06.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting07.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting08.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting09.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting10.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting11.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting12.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting13.svg
/usr/share/icons/Numix/24/animations/nm-vpn-connecting14.svg
/usr/share/icons/Numix/24/devices/nm-device-wired.svg
/usr/share/icons/Numix/24/devices/nm-device-wireless.svg
/usr/share/icons/Numix/24/status/nm-adhoc.svg
/usr/share/icons/Numix/24/status/nm-device-wired-autoip.svg
/usr/share/icons/Numix/24/status/nm-device-wired-secure.svg
/usr/share/icons/Numix/24/status/nm-device-wired.svg
/usr/share/icons/Numix/24/status/nm-device-wwan.svg
/usr/share/icons/Numix/24/status/nm-mb-roam.svg
/usr/share/icons/Numix/24/status/nm-no-connection.svg
/usr/share/icons/Numix/24/status/nm-secure-lock.svg
/usr/share/icons/Numix/24/status/nm-signal-0-secure.svg
/usr/share/icons/Numix/24/status/nm-signal-0.svg
/usr/share/icons/Numix/24/status/nm-signal-00-secure.svg
/usr/share/icons/Numix/24/status/nm-signal-00.svg
/usr/share/icons/Numix/24/status/nm-signal-100-secure.svg
/usr/share/icons/Numix/24/status/nm-signal-100.svg
/usr/share/icons/Numix/24/status/nm-signal-25-secure.svg
/usr/share/icons/Numix/24/status/nm-signal-25.svg
/usr/share/icons/Numix/24/status/nm-signal-50-secure.svg
/usr/share/icons/Numix/24/status/nm-signal-50.svg
/usr/share/icons/Numix/24/status/nm-signal-75-secure.svg
/usr/share/icons/Numix/24/status/nm-signal-75.svg
/usr/share/icons/Numix/24/status/nm-tech-3g.svg
/usr/share/icons/Numix/24/status/nm-tech-4g.svg
/usr/share/icons/Numix/24/status/nm-tech-cdma-1x.svg
/usr/share/icons/Numix/24/status/nm-tech-edge.svg
/usr/share/icons/Numix/24/status/nm-tech-evdo.svg
/usr/share/icons/Numix/24/status/nm-tech-gprs.svg
/usr/share/icons/Numix/24/status/nm-tech-hspa.svg
/usr/share/icons/Numix/24/status/nm-tech-umts.svg
/usr/share/icons/Numix/24/status/nm-vpn-active-lock.svg
/usr/share/icons/Numix/24/status/nm-vpn-lock.svg
/usr/share/icons/Numix/24/status/nm-vpn-standalone-lock.svg
/usr/share/icons/Numix/24/status/nm-wwan-tower.svg

Numix has different design for some icons <= 24 pixels and >= 32 pixels.

/usr/share/icons/Numix/48/devices/nm-device-wired.svg
/usr/share/icons/Numix/48/devices/nm-device-wireless.svg
/usr/share/icons/Numix/48/notifications/nm-device-wired.svg
/usr/share/icons/Numix/48/notifications/nm-device-wireless.svg
/usr/share/icons/Numix/48/notifications/nm-device-wwan.svg

For Nordic GTK theme I used to use Zafiro icons (as suggested by index.theme), but that theme has a **lot** of issues with dark themes (like Nordic).

Even with the known issues, Nordzy looks way better than Zafiro icons.

I already use harcode-tray. [I wrote a tool in bash](https://github.com/darkshram/aldos-tools) for quick theme testing. Hardcode-tray (sort of) works with liferea with some themes, usually picking the icons from Numix or Numix-circle because I modify some index.theme files to inherit one or the other because the completeness of Numix.

About creating an issue for Claws Mail in Harcode-Tray: Claws mail developers are currently doing some changes in the GTK3 branch, mostly modernizing the (very) outdated code (gui looks very awful with Nordic and other dark themes from Eliver Lara and other authors, so probably will be worth creating an issue at harcode-tray github page for one of their next releases).

![claws-mail-4 0 0-nordic](https://user-images.githubusercontent.com/10327500/129638742-5857f1db-47f8-4cf4-88b3-d024a4ce78c7.png)
Context/Personal opinion: screenshot of claws mail uses a custom icon theme for Claws Mail based on Papirus (/usr/share/claws-mail/themes/Papirus). Again, claws mail is making some changes to GUI related code, so may be will be worth creating an icon theme until some of their next releases. Most of the widgets currently used by claws mail are deprecated in latest GTK4 and will die together with GTK3 EOL. Hope we do not have to wait a whole decade for another major release of Claws Mail. I was thinking about swtiching to Geary, it's still buggy and feature incomplete. Claws Mail may have a very outdated GUI, but it works and it's feature complete.

**Comment by darkshram** [comment]
This is the screenshot with latest commit with Nordzy. Nice work!
![Captura de pantalla_2021-08-16_19-46-26](https://user-images.githubusercontent.com/10327500/129647512-8fe62256-ff45-4dbd-9f75-2aaedc85cbd6.png)

GTK Theme: Nordic
Icon theme: Nordzy (default)
Cursor Theme: Nordzy

Liferea will be a little tricky to solve. Some times works, sometimes don't. It depends on the panel height (my panel is 36 pixels height). In the screenshot it is still using the inherited icons from a previous theme tested (Vimix). You may need to create 22 and 24 pixels for liferea-unread and liferea-available. Tela and Vimix are the only known themes (from all the ones I usually test), that harcode-tray actually uses for liferea tray icon. Both themes have 16, 22 and 24 pixels icons for liferea-unread and liferea-available.

```
/usr/share/icons/Tela/16/panel/liferea-available.svg
/usr/share/icons/Tela/16/panel/liferea-unread.svg
/usr/share/icons/Tela/22/panel/liferea-available.svg
/usr/share/icons/Tela/22/panel/liferea-unread.svg
/usr/share/icons/Tela/24/panel/liferea-available.svg
/usr/share/icons/Tela/24/panel/liferea-unread.svg

/usr/share/icons/Vimix/16/panel/liferea-available.svg
/usr/share/icons/Vimix/16/panel/liferea-unread.svg
/usr/share/icons/Vimix/22/panel/liferea-available.svg
/usr/share/icons/Vimix/22/panel/liferea-unread.svg
/usr/share/icons/Vimix/24/panel/liferea-available.svg
/usr/share/icons/Vimix/24/panel/liferea-unread.svg
```
Original subject of this issue was solved (wine icon). Should I keep posting comments here or would you prefer I start a new issue?

**Comment by alvatip** [comment]
Thanks for your returns, they are very helpful !! :)
For the mails, I'm using Evolution, it looks good except for some icons that should be fixed later on. In the meantime, I will add those icons in my to-do to change them later.
I see that you have an icon “settings” in duplicate in your menu, maybe can you give me the name of the “wrong” one, I will modify it later. Same for the software center which is the symbolic icon ? (I should also create different icons depending on the distribution, this is on my to-do) 

I will 
- [ ] create a new folder “panel” to store the hardcoded tray icons, it might be easier for later. 
- [ ] re-create those nm-applet icons, I will probably take the inspiration from Numix or Vimix
- [ ] Create a 22, 24 (and I guess a 32 would be nice for large panel like yours?)
- [ ] finally, I will use Numix as a template to complete the system icons

Because completing the icons using Numix might take more time, I will probably close the issue once the nm-applet and liferea icons are solved.

**Comment by darkshram** [comment]
> I see that you have an icon “settings” in duplicate in your menu, maybe can you give me the name of the “wrong” one, I will modify it later. Same for the software center which is the symbolic icon ? (I should also create different icons depending on the distribution, this is on my to-do)

![Captura de pantalla_2021-08-16_19-46-26](https://user-images.githubusercontent.com/10327500/129704810-297de80f-d52f-44c5-8dd1-3dbb01c85ae8.png)

It's not really a duplicate.

The icon in the categories menu is the settings menu ('preferences-desktop' icon) which includes every tool under that category (desktop and system settings). The 'preferences-desktop' icon is present in Nordzy **but is missing in Nordzy-dark**.

The settings icon next to the lock screen icon is a shortcut to xfce4-settings-manager (preferences-desktop icon in Xfce <= 4.14 and org.xfce.settings.manager icon in Xfce >= 4.16) which is the equivalent to gnome-control-center or cinnamon-settings-manager.

System settings icon (applications-system) **is also missing in Nordzy-dark**.

Software center uses 'system-software-install' icon.

**Comment by darkshram** [comment]
There is another 'Apple' logo in the 'computer' icon (Nordzy/devices/scalable/computer.svg) and video-television (Nordzy/devices/scalable/video-television.svg).

![Captura de pantalla_2021-08-17_15-40-04](https://user-images.githubusercontent.com/10327500/129797514-e05a3c3c-8d43-4636-ab15-4256832d199b.png)

**Comment by alvatip** [comment]
Thanks, I will fix that ! probably this week-end :)

**Comment by alvatip** [comment]
So, because when completing the theme status icons with numix one it created some weird look I updated all the status icons to the numix one and updated the color to use the Nord colors. It works fine on fedora with gnome, I did not tried it on another linux desktop for now, I will try plasma later to see the results under this DE. Will probably try also on xfce but still need to install it :stuck_out_tongue: 
I will now work on your two last comments :wink:
