### ISSUE TITLE
[BUG] empty icons after optimization

### ISSUE THREAD

**Issue by mseveritt** [alvatip/Nordzy-icon#22]
**Describe the bug**
After the optimization, some icons got empty, e.g. applications-internet and applications-system

**To Reproduce**
E.g. open Cinnamon menu and see missing icons.

**Expected behaviour**
Icons not empty anymore.

**Screenshots**
Here is a complete list:
![grafik](https://user-images.githubusercontent.com/61334079/157615444-84fa1481-a9d4-4983-bc01-fdd41dbb5056.png)

**Desktop**
Cinnamon 5.2.7

**Comment by alvatip** [comment]
Yup indeed, something might have gone wrong when running my script for those icons... Thanks for noticing and reporting, I will fix this this weekend!
