### ISSUE TITLE
[BUG] Zoom (deb) tray icon is not the one from Nordzy

### ISSUE THREAD

**Issue by mseveritt** [alvatip/Nordzy-icon#23]
**Describe the bug**
If Zoom is started, the tray icon does not follow the design of the theme.

**To Reproduce**
Steps to reproduce the behaviour:
Start Zoom.

**Expected behaviour**
The Zoom tray icon is in the design of the theme.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/61334079/158016431-7bf9e278-86ec-40da-8651-d3710c92c56c.png)
vs
![grafik](https://user-images.githubusercontent.com/61334079/158016423-3a15ba69-9f4d-4126-b89f-f5eef983be14.png)

**Desktop**
Linux Mint 20.3 Cinnamon 5.2.7
Zoom is installed as deb-package.

**Additional context**
I already tried to make it work but without success. :-(

**Comment by alvatip** [comment]
Thanks for the report,
I will work on it as soon as the previous issue is fixed

**Comment by mseveritt** [comment]
It might be impossible to fix: cf. https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2821

**Comment by alvatip** [comment]
Yes indeed, even in hardcoded-tray they are not able to fix it since this is a closed source app...
