### ISSUE TITLE
[ICON] LibreOffice Start Center, Redshift

### ISSUE THREAD

**Issue by mseveritt** [alvatip/Nordzy-icon#24]
Application name: LibreOffice, Redshift
Icon name if you know it: 
- libreoffice-startcenter.svg
- redshift.svg

Use tray? Redshift is already implemented.
Small description and/or a link to the official webpage:
For LibreOffice, just the startcenter is missing. 
For Redshift, just the Application icon is missing.

**Comment by alvatip** [comment]
All should be good now ! :tada:

**Comment by mseveritt** [comment]
Yes, thanks a lot, also for your optimizations of my proposals. I really like redshift.

**Comment by alvatip** [comment]
You are very welcome! Thanks for your contribution!
