### ISSUE TITLE
[ICON] Strawberry player

### ISSUE THREAD

**Issue by tneo** [alvatip/Nordzy-icon#29]
Application name: Strawberry player
Icon name if you know it: org.strawberrymusicplayer.strawberry
Original icon image: https://www.strawberrymusicplayer.org/pictures/strawberry64.png
Use tray? Yes
Small description and/or a link to the official webpage: https://www.strawberrymusicplayer.org/

**Comment by alvatip** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue](https://trello.com/c/o9IKngne/10-issue)

**Comment by alvatip** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue](https://trello.com/c/o9IKngne/10-issue)

**Comment by alvatip** [comment]
I already added the icon for the app, I will complete the tray icon later on this week :wink:
