### ISSUE TITLE
[ICON] Support for Xfce 4.16 rdns icons.

### ISSUE THREAD

**Issue by darkshram** [alvatip/Nordzy-icon#3]
This is the current look of xfce4-settings-manager with current Nordzy icon theme. Added some context to the screenshot because some tools are not really from Xfce.

![xfce4-manager-4 16](https://user-images.githubusercontent.com/10327500/129689411-bc58b727-e8b2-46f5-a65e-b529f86b6f52.png)
Context: Icons within a red square are not part of Xfce. They are 3rd party tools I just integrated into xfce4-settings-manager because I felt final users may like to find them within a single tool.

This is the [new name schema for Xfce 4.16:](https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons)

<table>
	<thead>
	<tr>
		<th>Old icon name</th><th>New icon name</th>
	</tr>
	</thead>
	<tbody>
    <tr>
		<td>xfce4-power-manager-settings</td><td>org.xfce.powermanager</td>
	</tr>
	<tr>
		<td>xfce4-panel</td><td>org.xfce.panel</td>
	</tr>
	<tr>
		<td>xfce4-panel-menu</td><td>org.xfce.panel.applicationsmenu</td>
	</tr>
	<tr>
		<td>system-log-out</td><td>org.xfce.panel.actions</td>
	</tr>
	<tr>
		<td>x-office-calendar</td><td>org.xfce.panel.clock</td>
	</tr>
	<tr>
		<td>folder</td><td>org.xfce.panel.directorymenu</td>
	</tr>
	<tr>
		<td>application-x-executable</td><td>org.xfce.panel.launcher</td>
	</tr>
	<tr>
		<td>xfce4-workspaces</td><td>org.xfce.panel.pager</td>
	</tr>
	<tr>
		<td>list-remove-symbolic</td><td>org.xfce.panel.separator</td>
	</tr>
	<tr>
		<td>user-desktop</td><td>org.xfce.panel.showdesktop</td>
	</tr>
	<tr>
		<td>preferences-system-windows</td><td>org.xfce.panel.tasklist</td>
	</tr>
	<tr>
		<td>preferences-system-windows</td><td>org.xfce.panel.windowmenu</td>
	</tr>
	<tr>
		<td>xfce4-session</td><td>org.xfce.session</td>
	</tr>
	<tr>
		<td>system-log-out</td><td>xfsm-logout</td>
	</tr>
	<tr>
		<td>system-reboot</td><td>xfsm-reboot</td>
	</tr>
	<tr>
		<td>system-shutdown</td><td>xfsm-shutdown</td>
	</tr>
	<tr>
		<td>system-suspend</td><td>xfsm-suspend</td>
	</tr>
	<tr>
		<td>system-hibernate</td><td>xfsm-hibernate</td>
	</tr>
	<tr>
		<td>system-suspend-hibernate</td><td>xfsm-hibernate</td>
	</tr>
	<tr>
		<td>system-users</td><td>xfsm-switch-user</td>
	</tr>
	<tr>
		<td>preferences-system</td><td>org.xfce.settings.editor</td>
	</tr>
	<tr>
		<td>preferences-desktop</td><td>org.xfce.settings.manager</td>
	</tr>
	<tr>
		<td>preferences-desktop-accessibility</td><td>org.xfce.settings.accessibility</td>
	</tr>
	<tr>
		<td>preferences-desktop-theme</td><td>org.xfce.settings.appearance</td>
	</tr>
	<tr>
		<td>xfce4-color-settings</td><td>org.xfce.settings.color</td>
	</tr>
	<tr>
		<td>video-display</td><td>org.xfce.settings.display</td>
	</tr>
	<tr>
		<td>preferences-desktop-keyboard</td><td>org.xfce.settings.keyboard</td>
	</tr>
	<tr>
		<td>preferences-desktop-default-applications</td><td>org.xfce.settings.preferred-applications</td>
	</tr>
	<tr>
		<td>preferences-desktop-peripherals</td><td>org.xfce.settings.mouse</td>
	</tr>
	<tr>
		<td>edit-find</td><td>org.xfce.appfinder</td>
	</tr>
	<tr>
		<td>drive-removable-media</td><td>org.xfce.volman</td>
	</tr>
	<tr>
		<td>Thunar</td><td>org.xfce.thunar</td>
	</tr>
	<tr>
		<td>preferences-desktop-screensaver</td><td>org.xfce.ScreenSaver</td>
	</tr>
	<tr>
		<td>utilities-terminal</td><td>org.xfce.terminal</td>
	</tr>
	<tr>
		<td>utilities-terminal</td><td>org.xfce.terminal-settings</td>
	</tr>
	<tr>
		<td>accessories-text-editor</td><td>org.xfce.mousepad</td>
	</tr>
	<tr>
		<td>applets-screenshooter</td><td>org.xfce.screenshooter</td>
	</tr>
	<tr>
		<td>utilities-system-monitor</td><td>org.xfce.taskmanager</td>
	</tr>
	<tr>
		<td>xfce4-notifyd</td><td>org.xfce.notification</td>
	</tr>
	<tr>
		<td>xfce4-dict</td><td>org.xfce.Dictionary</td>
	</tr>
	<tr>
		<td>catfish</td><td>org.xfce.catfish</td>
	</tr>
	<tr>
		<td>gtk-network</td><td>org.xfce.gigolo</td>
	</tr>
	<tr>
		<td>parole</td><td>org.xfce.parole</td>
	</tr>
	<tr>
		<td>ristretto</td><td>org.xfce.ristretto</td>
	</tr>
	<tr>
		<td>xfburn</td><td>org.xfce.xfburn</td>
	</tr>
	<tr>
		<td>xfdashboard</td><td>org.xfce.xfdashboard</td>
	</tr>
</tbody>
</table>

I have a 'shortcut method' to create the rdns icons. Saves some time and work. First I used the [official Xfce list for rdns icons](https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons), then created a two column text file with this table data and saved it as ~/new-rdns-icons-xfce4-4.16.txt. Then used the following script, which basically looks for the old xfce4 icons within the src sub-folders, then tries to create a symlink for new rdns icon at the same location. The script only creates the symlink with relative path if the old xfce4 icon (png/svg) does exist and it does not overwrite any previously existent symlink (unless -fsr is used instead of -lr):

```
cd Nordzy-icon
for dir in `find ./src -type d -name "*"`
do
    cd ${dir} && \
    while read old new
    do
        if [ -e ${old}.png ]; then ln -sr ${old}.png ${new}.png; fi
        if [ -e ${old}.svg ]; then ln -sr ${old}.svg ${new}.svg; fi
    done < ~/new-rdns-icons-xfce4-4.16.txt
    cd -
done
find ./src -type l -name "*" |xargs git add
```

Simple, but effective. The catch: if there is no previous old Xfce icon, there will not be a new Xfce rdns icon.

There is also this python script [https://gist.github.com/bluesabre/582d886a02c793285f4e3081df9b2a3c](https://gist.github.com/bluesabre/582d886a02c793285f4e3081df9b2a3c). Have not tested it, but basically does the same as my bash script, but with harder to read code.

I can make a PR if you want, but I think you may like to play a little with both alternatives to check and test the results.

**Comment by alvatip** [comment]
I will fix that as soon as I'm over with the other bug :wink: 
Feel free to create a PR, even thought I don't think any of these icons are already created (well at least none that I remember)... And if this is the case, they are probably symlinks that should be deleted and replaced by a proper icon. :stuck_out_tongue:

**Comment by darkshram** [comment]
I tested it yesterday. Some of them are present. This is the list of the new icons created with the script, symlinking to the existent old Xfce icons (still WhiteSur styled).

```
src/actions/16/org.xfce.appfinder.svg
src/actions/16/org.xfce.panel.actions.svg
src/actions/16/xfsm-logout.svg
src/actions/22/org.xfce.appfinder.svg
src/actions/22/org.xfce.panel.actions.svg
src/actions/22/xfsm-hibernate.svg
src/actions/22/xfsm-logout.svg
src/actions/22/xfsm-shutdown.svg
src/actions/22/xfsm-suspend.svg
src/actions/24/org.xfce.appfinder.svg
src/actions/24/org.xfce.panel.actions.svg
src/actions/24/xfsm-hibernate.svg
src/actions/24/xfsm-logout.svg
src/actions/24/xfsm-shutdown.svg
src/actions/24/xfsm-suspend.svg
src/actions/32/org.xfce.panel.actions.svg
src/actions/32/xfsm-hibernate.svg
src/actions/32/xfsm-logout.svg
src/actions/32/xfsm-reboot.svg
src/actions/32/xfsm-shutdown.svg
src/actions/32/xfsm-suspend.svg
src/actions/32/xfsm-switch-user.svg
src/actions/symbolic/org.xfce.panel.separator.svg
src/apps/scalable/org.xfce.settings.editor.svg
src/apps/scalable/org.xfce.volman.svg
src/devices/16/org.xfce.volman.svg
src/devices/22/org.xfce.volman.svg
src/devices/24/org.xfce.volman.svg
src/devices/scalable/org.xfce.volman.svg
src/mimes/16/org.xfce.panel.clock.svg
src/mimes/16/org.xfce.panel.launcher.svg
src/mimes/22/org.xfce.panel.clock.svg
src/mimes/22/org.xfce.panel.launcher.svg
src/mimes/scalable/org.xfce.panel.clock.svg
src/mimes/scalable/org.xfce.panel.launcher.svg
src/places/16/org.xfce.panel.directorymenu.svg
src/places/22/org.xfce.panel.directorymenu.svg
src/places/24/org.xfce.panel.directorymenu.svg
src/places/scalable/org.xfce.panel.directorymenu.svg
src/places/scalable/org.xfce.panel.showdesktop.svg
```
Will make a PR before the weekend.

**Comment by alvatip** [comment]
Sweet, thanks !!
