### ISSUE TITLE
[BUG] Installing theme through Pling.com results in all files extracted in ~/.local/share/icons

### ISSUE THREAD

**Issue by tneo** [alvatip/Nordzy-icon#34]
When you install the icons through the Pling.com site (or KDE system settings) the files are extracted into the ~/.local/share/icons and not in ~/.local/share/icons/Nordzy

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to: https://www.pling.com/p/1686927
2. Click on the "Install" button
3. Select desired style.
4. Wait until finished
5. Open ~/.local/share/icons
6. All files are extracted here

Or replace 1 & 2:
1. Open KDE System Settings > Appearance > Icons
2. Click "Get New Icons" and search for Nordzy

Extraction/ Installation results in a correct directory in the icons directory, so that KDE System Settings recognizes the theme correctly.

**Desktop**
Operating System: openSUSE Tumbleweed 20220322
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.16.15-1-default (64-bit)
Graphics Platform: X11

**Comment by alvatip** [comment]
This will most likely be fixed this weekend ! Thanks for reporting :wink:

**Comment by alvatip** [comment]
This was most likely an error when creating the archives, this should be fixed now, I tested it on kde system settings and using ocs-url and both worked fine. 
Maybe can you confirm that it works also fine using the pling-store app before I close the issue ? 
Thanks

**Comment by tneo** [comment]
Yeah, it works correctly now.
