### ISSUE TITLE
[BUG] Inconsistency for thunderbird

### ISSUE THREAD

**Issue by mseveritt** [alvatip/Nordzy-icon#36]
**Describe the bug**
The app icon and the status icon for thunderbird are different. 
At least for Cinnamon, for menu and panel, the status icon is used instead of the very beautiful app one.

**To Reproduce**
Look at Thunderbird icon in menu and panel.

**Expected behaviour**
The app icon is used for menu and panel.
This could be done by either a removal of the thunderbird icon from status or an alignment of the icons if possible. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/61334079/162030797-ce012786-20b2-4bc7-aa7c-2ff1fe421a2e.png)

**Desktop**
LMDE 5 Cinnamon 5.2.7, panel height 43, menu icon size 23

**Comment by alvatip** [comment]
Thanks for reporting, I will check it this weekend

**Comment by alvatip** [comment]
It should be fixed now, I tested it in a vm, maybe could you confirm ? thanks

**Comment by mseveritt** [comment]
Also this is looks fine now:
![grafik](https://user-images.githubusercontent.com/61334079/162594320-da4a1a39-db6b-434d-b5ed-d898630e726c.png)
Thanks!
