### ISSUE TITLE
[BUG] timeshift icon shows black arrow tip

### ISSUE THREAD

**Issue by mseveritt** [alvatip/Nordzy-icon#37]
**Describe the bug**
The timeshift icon displays a black arrow tip although it does not seem supposed to do so.

**To Reproduce**
Open timeshift.svg in inkscape vs in a picture viewer. Also in panel and menu, the icon appears with black arrow tip.

**Expected behaviour**
Assuming that the black arrow tip is not intended, it should be in a nordic white/grey as the rest.

**Screenshots**
Picture Viewer
![grafik](https://user-images.githubusercontent.com/61334079/162290572-dd3ef373-1807-425e-91fa-5287ded47d68.png)

In inkscape:
![grafik](https://user-images.githubusercontent.com/61334079/162290835-550aedfa-d7b6-414c-97ff-65ace8ff3da1.png)

**Desktop**
Cinnamon 5.2.7 and XFCE 4.16

**Additional context**
I already checked in inkscape and I have no clue.

**Comment by alvatip** [comment]
I will check it this weekend, thanks for reporting :+1:

**Comment by alvatip** [comment]
This should also be fixed, could you confirm that this is fixed ? thanks

**Comment by mseveritt** [comment]
Looks perfectly fine:
![grafik](https://user-images.githubusercontent.com/61334079/162594252-fdd24811-2319-4491-8472-14ed82142a48.png)
![grafik](https://user-images.githubusercontent.com/61334079/162594262-ab29e65f-044a-4b92-969f-b875be66528c.png)
