### ISSUE TITLE
[BUG] Firefox Icon

### ISSUE THREAD

**Issue by mpaunovic** [alvatip/Nordzy-icon#41]
Hi all,

Pinkish background color of the Firefox icon makes the logo barely visible. Maybe a brighter/darker shade of pink or even completely different color would be a better match?

I've attached a screenshot.

Thank you so much for this lovely icon pack!

![ss](https://user-images.githubusercontent.com/17993741/169698262-654cb896-ec48-469a-b2b6-9a57c81a85f6.png)

**Comment by MolassesLover** [comment]
I [updated the icon](https://github.com/alvatip/Nordzy-icon/pull/44), giving it a white background. I hope it helps! If it doesn't get merged, you can `checkout` the change using the [GitHub command-line tool](https://github.com/cli/cli/blob/trunk/docs/install_linux.md). 

Here is the command:
```zsh
➜ gh pr checkout 44
```

**Comment by mpaunovic** [comment]
It does help, thank you!

**Comment by alvatip** [comment]
Thanks @MolassesLover I will check and commit your PR tomorrow, sorry for the delay but got some deadline for work currently, this will be better in a few days :wink:

**Comment by MolassesLover** [comment]
> Thanks @MolassesLover I will check and commit your PR tomorrow, sorry for the delay but got some deadline for work currently, this will be better in a few days :wink: 

No pressure! I'm just happy to help
