### ISSUE TITLE
Strange USB icon looking

### ISSUE THREAD

**Issue by 64542426** [alvatip/Nordzy-icon#46]
**Describe the bug**
USB Icon it seems a bit strange to me

**Screenshots**
![2022-05-28--1653770280_201x184_scrot](https://user-images.githubusercontent.com/35492934/170838866-45034ec2-1f9a-4e24-b523-f420fe856e3b.png)
^I mean the last icon

**Additional context**
I have seen this icon exactly the same on other icons packages if i am not wrong WhiteSur or something similar.
Maybe it's like that at upstream? or it means to be so, but to me looks a bit strange.

**Comment by alvatip** [comment]
Thanks for reporting :+1: 
I will also check on my fedora and fix this!

**Comment by alvatip** [comment]
Did brought some modifications to the icon in my last commit, could you maybe confirm that this is fixed (currently away and don't have any USB with me to check...) ?

**Comment by 64542426** [comment]
Just updated icons now, it looks much better now.
![2022-06-02--1654161141_194x173_scrot](https://user-images.githubusercontent.com/35492934/171574184-8603a1bd-18c3-439b-a605-e479fba965ad.png)
Close this ticket as Solved. Thank you very much for this adjustment.
