### ISSUE TITLE
[FEATURE] Light icons variant for dark bar

### ISSUE THREAD

**Issue by Hotteterre** [alvatip/Nordzy-icon#47]
Hello, thank you for the great icons! I only experienced some problem using them with a light theme (Nordic Polar) and a dark bar: setting light icons, some of the ones on the bar result invisible, while with dark icons the latter are difficult to see in some applications.

Could you consider to release a variant of light icons for use with light theme and a dark bar? For example, as in Flat Remix ([https://www.opendesktop.org/p/1012430](https://www.opendesktop.org/p/1012430)).

Thank you so much for the great work!

**Comment by alvatip** [comment]
Thanks for your comment, I surely can do that, I will keep you updated here :wink:

**Comment by alvatip** [comment]
It should work fine with the last commit :wink: Could you maybe try and confirm ?

**Comment by Hotteterre** [comment]
Thank you, installing from source I can select the light and dark variants, and they work. But with the last version I have a new issue: if I install all the color variants, whatever color I select, I obtain default folders. Excuse me for bothering you, but I cant0t figurate if it depends from the package or from my settings...

**Comment by alvatip** [comment]
Yep, I think I made a mistake when modifying the install.sh file, I will check that
Thanks for reporting, I am glad someone tells me that there is an issue so I can fix it :wink:

**Comment by alvatip** [comment]
I did a mistake in the name of a variable in my install.sh script. Now all should work perfectly, -t allow to install color theme and the -p option switch the panel color (if color is dark, panel will be light and vice versa)
Could you please confirm that it work also fine for you with the last commit ? :smile:

**Comment by Hotteterre** [comment]
Wow, it's perfect!
If I can ask: would be possible to install all the colors with all the light/dark variants? It'd be very convenient when installing (and updating) from a package manager: there would be no need to change anything, simply choose the color and the variant.
Thank you so much for all! :smile:

**Comment by alvatip** [comment]
Sure, I will check that :wink:

**Comment by alvatip** [comment]
It should work fine using: ./install.sh -t or ./install.sh --total :+1:

**Comment by Hotteterre** [comment]
Yes!!! It works with --total, perhaps because -t is already used to select the theme?

**Comment by alvatip** [comment]
Thanks, that is completely right, I will leave the long option and remove the short -t so it does not overlap with the choice for the theme. I will close the issue when done 😉 Thanks for you contribution 👍

**Comment by Hotteterre** [comment]
Thanks to you for the fabulous work! :smile:
