### ISSUE TITLE
[BUG] ./install.sh: line 64: /bin/sed: Argument list too long

### ISSUE THREAD

**Issue by darkshram** [alvatip/Nordzy-icon#51]
**Describe the bug**
Number of files to process with sed is to big to be used as regular user. Number of files exceeds `nofile` limit of any Linux system for regular users.

```
./install.sh: line 64: /bin/sed: Argument list too long
```

**To Reproduce**
Install Nordzy-icon as regular user.

**Expected behaviour**
Should process line 64 command without "Argument list too long".

**Desktop**
ALDOS 1.4.

**Additional context**
Instead of:
```
sed -i "s/${hex_dark}/${hex_white}/g" "${THEME_DIR}"/{actions,devices,places,status}/{16,22,24}/*
```
You may use the following as workaround:
```
  for ICONTYPE in actions devices places status 
  do
    for i in 16 22 24
    do
      sed -i "s/${hex_dark}/${hex_white}/g" "${THEME_DIR}"/${ICONTYPE}/${i}/*
    done
  done
  ```
This way, the number of files processed by sed will not exceed the `nofile` limit of system. Certainly this would be fixed running `ulimit`, but for _regular-non-technical_ users will be easier to modify the way files are processed from the install script.

This is the patch for install.sh. Do not think it worth to make a push request, but if you ask, I'll do it.
```
--- Nordzy-icon-f1734de91f79260fc6a08ebb645fefe8242d122a.orig/install.sh	2022-06-21 12:37:27.286806827 -0500
+++ Nordzy-icon-f1734de91f79260fc6a08ebb645fefe8242d122a/install.sh	2022-06-21 12:47:51.068027755 -0500
@@ -61,7 +61,13 @@
 }
 
 change_color(){
-  sed -i "s/${hex_dark}/${hex_white}/g" "${THEME_DIR}"/{actions,devices,places,status}/{16,22,24}/*
+  for ICONTYPE in actions devices places status 
+  do
+    for i in 16 22 24
+    do
+      sed -i "s/${hex_dark}/${hex_white}/g" "${THEME_DIR}"/${ICONTYPE}/${i}/*
+    done
+  done
   sed -i "s/${hex_dark}/${hex_white}/g" "${THEME_DIR}"/actions/32/*
   sed -i "s/${hex_dark}/${hex_white}/g" "${THEME_DIR}"/{actions,apps,categories,emblems,devices,mimes,places}/symbolic/*
 }
```

**Comment by alvatip** [comment]
Thanks for noticing, I will modify it today 👍

**Comment by alvatip** [comment]
Should be fine now :smile:
