### ISSUE TITLE
[ICON] OnlyOffice Desktop Editors

### ISSUE THREAD

**Issue by sm-wilson** [alvatip/Nordzy-icon#52]
Application name: ONLYOFFICE Desktop Editors
Icon name if you know it: 
Original icon image: (https://docs.cloudron.io/img/onlyoffice-logo.png)
Use tray? No
Small description and/or a link to the official webpage: https://www.onlyoffice.com/

**Comment by alvatip** [comment]
Icon is created and should work properly, if this is not the case, just reopen this issue :wink:

**Comment by sm-wilson** [comment]
Awesome, thanks for the quick turnaround on these!
