### ISSUE TITLE
[ICON] Chromium Web Browser

### ISSUE THREAD

**Issue by sm-wilson** [alvatip/Nordzy-icon#53]
Application name: Chromium Web Browser
Icon name if you know it: 
Original icon image: (https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/chromium.png)
Use tray? No
Small description and/or a link to the official webpage: All-blue version of Google Chrome logo/icon. Current version has the correct shape but is only gray. 
![chromium-gray](https://user-images.githubusercontent.com/57883270/175407396-5410de10-8049-483f-a6c9-96863f81d95e.png)

**Comment by alvatip** [comment]
Which distribution of Linux do you use ? Also, did you install it through the package manager of your distro or flatpak?  I already have a chromium icon in the theme, so I think that the naming of the icon is incorrect and I should add a symlink with the correct name for your version

**Comment by sm-wilson** [comment]
Hello,

I'm running openSUSE Tumbleweed with the Cinnamon desktop. If I remember
right I downloaded directly from GitHub and used the install script. I
don't see Nordzy when searching the repos.

**Comment by alvatip** [comment]
Thanks 😊 I will check that tomorrow

**Comment by alvatip** [comment]
I think it should be fixed with the last commit. Could you confirm that it works fine for you? I am on Fedora and the icon is displayed properly.

**Comment by sm-wilson** [comment]
Thanks for the follow up. The correct icon does appear now. Thanks again!
