### ISSUE TITLE
[ICON]

### ISSUE THREAD

**Issue by mbacou** [alvatip/Nordzy-icon#55]
overGrive (overgrive)
Stata (stata)
QGIS (org.qgis.qgis)
GRASS (grass78)
YouTube Downloader (youtubedl-gui)
emacs
jupyterLab
org.kde.kate
org.kde.yakuake
Slack
xygrib
Google Docs / Google Sheets

Great work. Thank you!

**Comment by alvatip** [comment]
I will probably do that during this week and will keep the list below updated as I create them

- [ ] overGrive (overgrive)
- [ ] Stata (stata)
- [ ] QGIS (qgis)
- [ ] GRASS (grass78)
- [ ] YouTube Downloader (youtubedl-gui)
- [ ] emacs
- [ ] jupyterLab
- [ ] org.kde.kate
- [ ] org.kde.yakuake
- [ ] Slack
- [ ] xygrib
- [ ] Google Docs / Google Sheets

**Comment by mbacou** [comment]
Thanks, no rush. Aside from XyGrib, these are very common applications, so probably useful to many.

**Comment by alvatip** [comment]
All icons are created ! However, I am not sure I named all the icons properly, so could you tell me which are working fine and wich are not ? thanks :wink:

**Comment by mbacou** [comment]
Thanks, perfect! All working for me on Kubuntu, but I'm used to editing my `~/.local/share/applications/*.desktop` files.
