### ISSUE TITLE
[ICON] Flameshot Tray Icon

### ISSUE THREAD

**Issue by YahiaJr** [alvatip/Nordzy-icon#57]
Application name: Flameshot
Use tray? yes

Could you please add the Flameshot monochrome tray icon version instead of the colored one.

![image](https://user-images.githubusercontent.com/37158766/178979126-40ae6a18-090b-448d-a2b9-9b0970343a57.png)

**Comment by alvatip** [comment]
Sure! Just finishing some deadlines before 😉

**Comment by alvatip** [comment]
Changed the icon for the tray to the monochrome one, so it should be fine now. Could you confirm ? I tried it on my fedora with gnome and it worked fine

**Comment by YahiaJr** [comment]
It's still the same colored one for me. However I found the monochrome icon under `/usr/share/icons/Nordzy/status/scalable` , don't know why its not working really!

I'm using Kubuntu 22.04

Aside form that, the new icon for the Kate application is VERY beautiful. Really appreciate your amazing work 🙏.

**Comment by MolassesLover** [comment]
> It's still the same colored one for me. However I found the monochrome icon under `/usr/share/icons/Nordzy/status/scalable` , don't know why its not working really!
> 
> 
> 
> I'm using Kubuntu 22.04
> 
> 
> 
> Aside form that, the new icon for the Kate application is VERY beautiful. Really appreciate your amazing work 🙏.

Would you mind sending the Flameshot desktop file? It's usually in `/usr/share/applications`, `/usr/local/share/applications`, or `$HOME/.local/share/applications/`. That would let me and @alvatip know what icon Flameshot is looking for, without having to run Kubuntu

**Comment by YahiaJr** [comment]
Sure. Here it is.

[org.flameshot.Flameshot.desktop.txt](https://github.com/alvatip/Nordzy-icon/files/9479592/org.flameshot.Flameshot.desktop.txt)

**Please note: I appended the _txt_ extension because github didn't support sending it as is**

**Comment by alvatip** [comment]
Thanks @MolassesLover and @YahiaJr ! I added a symlink for the flameshot icon using the same name as mentionned in the .desktop file. I believe it should work fine now. Could you try the last commit through a clone and using the installation script ? Thanks :wink:
