### ISSUE TITLE
[ICON] Kitty Terminal

### ISSUE THREAD

**Issue by pgosar** [alvatip/Nordzy-icon#59]
Application name: Kitty Terminal
Original icon 
<img width="175" alt="Screen Shot 2022-07-19 at 3 20 58 PM" src="https://user-images.githubusercontent.com/55164602/179841166-1f69d657-02f7-44d5-95e6-fbf43fce4173.png">

Disclaimer: the icon is actually just the cat, no background. But of course it would probably fit in better with one since the rest of the icons are actually squares.

Use tray? no
Small description and/or a link to the official webpage:
https://sw.kovidgoyal.net/kitty/

I really like your icons by the way! I've been recommending them to people I know that use Nord. Really great job with them and thanks for taking the time to add new requests all the time.

Let me know if you need any more info

**Comment by alvatip** [comment]
Hey, thanks for reporting 😉 Could you post an image of the icon that is displayed on your computer please?

**Comment by alvatip** [comment]
Thanks! So I looked on my system and inside the github project and found no reasons that could explain this behavior, the icon is made and naming should be right... Could you tell me what is the icon name mentioned in the .desktop file of kitty ? In case you don't know how/where to find them, just run
`cd /usr/share/applications/` then
`find . -name "*kitty*"` which should list you some file (on my system I have kitty-open.desktop and kitty.desktop) and finally open them (a simple xdg-open _filename_ should do the trick)
You should get something like this
![image](https://user-images.githubusercontent.com/84344248/180071836-e5009353-8e9f-4d3d-8dce-1d4f5245bfb8.png)
The line stating "Icon=..." is what I am looking for

**Comment by pgosar** [comment]
I did a bit of poking around after you mentioned the icon was already included, and for some reason it looked like the path for the kitty icon never updated when I installed it. Not sure why this would be, but I manually updated the path to the kitty icon, and it does work now. Here are the instructions I followed: https://sw.kovidgoyal.net/kitty/binary/

**Comment by alvatip** [comment]
Great ! Problem solved then ? Like I thought, naming in kitty.desktop was probably different from the one I mention in the theme.

**Comment by pgosar** [comment]
Yeah, I don't recall making any changes to the desktop files prior to downloading the icon pack so it is weird that it didn't auto update to the new icon, but sometimes weird things just happen ¯\_(ツ)_/¯. Anyways, yeah problem solved!
