### ISSUE TITLE
Inconsistent backdrops

### ISSUE THREAD

**Issue by MolassesLover** [alvatip/Nordzy-icon#71]
## About

Throughout all icons there are two types of backdrop shadows:

### 1. Merged

![Screenshot from 2022-09-04 17-47-35](https://user-images.githubusercontent.com/60114762/188322219-fd76f932-5b91-408e-b478-6d197d74750f.png)

### 2. Separate

![Screenshot from 2022-09-04 17-46-47](https://user-images.githubusercontent.com/60114762/188322224-285583ce-b5b7-4d13-baca-19234177a4de.png)

## The Issue

The first is incredibly hard to notice, since the backdrop is extremely subtle. It would arguably be only realistically visible with an OLED or QLED display. Because of this I have inadvertently contributed a ton of icons that do probably not utilise the appropriate backdrop settings, and have maybe even have two layers of backdrops.

You can see here that the Blender, and UPBGE icons have a much darker backdrop shadow, relative to other icons. Some icons like the clock icons don't have a noticeable backdrop at all.

![Screenshot from 2022-09-04 17-54-47](https://user-images.githubusercontent.com/60114762/188322662-751a1901-28b2-462a-bcb1-797865dc8076.png)

## The Fix

The best way to fix this is to standardise a way of using backdrop shadows. I think keeping the backdrop separate would be the best, as it allows for easier alteration of gradients.

Maybe we can have a branch specifically to overhaul the backdrop shadows? This could be a massive issue in the long-term.

Sorry if I missed anything, I still don't have too much experience with `.svg` files.

**Comment by alvatip** [comment]
Thanks for noticing this @MolassesLover ! :+1: 
There is indeed some inconsistency there, but that is not a big deal! I will have a look to make a standardise backdrop shadows, then I will write a script to find and replace them all at once without having to do it manually :wink: 

Blender and UPBGE backdrops are more noticeable because the offset and darkness of the backdrop shadows are more important compare to the other. 

It is also good to know that in fact merged and separate are usually the same, when optimizing the icons, Inkscape will just group some shape such as the background and the backdrop shadow to spare some text and have lighter .svg. They can be separated with ctrl + g when selected

**Comment by MolassesLover** [comment]
My bad, I'll use the outline view now, and keep an eye on the objects/layers. Also, how do you plan on making the script?

**Comment by alvatip** [comment]
Should be fixed now !! :+1: I do not think I missed any of the icons nor made mistake, but we will see with time and uses.
For my script, I used the 'sed' command with a regex to select only the shadows of most of the icons (something like 260 on 300) and replace it with the SVG code of the new shadow. Then I modified the other 40 manually :stuck_out_tongue: 

This is basically what I came up with: 
```
#!/bin/bash
new_shadow='<rect transform="matrix(.99138 0 0 1 .072989 .0019055)" x=".79375" y=".90545" width="15.346" height="15.346" rx="3.0526" ry="3.0526" fill="#2e3440" filter="url(#filter1178)" opacity=".45" stroke-width="1.2489" style="mix-blend-mode:normal"\/>'

for icon in $HOME/github/Nordzy-icon/src/apps/scalable/*; do
	sed -i "s/<rect.*width=\"15.346\" height=\"15.346\" rx=\"3.0526\" ry=\"3.0526\" fill=\"#2e3440\".*\/>$/${new_shadow}/g" ${icon}
done
```

**Comment by alvatip** [comment]
I created a new branch where i modified all the backdrop shadows with a full black. Could you try this dev branch ? My desktop does not have a full background with nord color so I don't have the issue... :stuck_out_tongue: Thanks

**Comment by MolassesLover** [comment]
It works fine! Though, the black seems to be at 45%, which, in my opinion, I find a bit too strong. I would prefer it if you set it to 15%, which is what I used (I think).

![Screenshot from 2022-09-22 21-11-23](https://user-images.githubusercontent.com/60114762/191832624-40c4dfa4-2c10-42bf-8900-1d8bd9430078.png)

![Screenshot from 2022-09-22 21-13-41](https://user-images.githubusercontent.com/60114762/191832908-8bd9a412-e0d3-423c-ae41-b6962d80f4f4.png)

**Comment by alvatip** [comment]
That is better, but you are right, the shadow is too strong in opacity. I will try 15% as you suggest!

**Comment by MolassesLover** [comment]
Awesome, thank you so much!

**Comment by alvatip** [comment]
Still in the black_shadows branch, I updated the opacity to 15%. Could you give it a try ? Thanks

**Comment by MolassesLover** [comment]
It looks perfect! Thank you so much, again. 

![Screenshot from 2022-09-25 14-03-31](https://user-images.githubusercontent.com/60114762/192142550-8a464a11-67b8-48f3-a6f6-e398527ff527.png)

Please let me know if any of my pull requests have the wrong backdrop, I'd fix it in a heartbeat.
