### ISSUE TITLE
Only generate the cache file once?

### ISSUE THREAD

**Issue by frosetrain** [alvatip/Nordzy-icon#74]
When installing many variants of the icons, install.sh runs `gtk-update-icon-cache` after every variant is copied, which makes the installation process slow. Is it possible to only run `gtk-update-icon-cache` once, after all the icons are copied over to the correct location? Or is there a reason for doing this many times?

**Comment by alvatip** [comment]
Hey, sorry for my late reply, time is going fast these days :smile: 
I know that it render the installation process quite slow, unfortunately I should run this command for each new directory created (aka, each new icon theme)...
I think the icon theme might also work without creating a cache file, I will try it and if it also works fine without `gtk-update-icon-cache`I will create an option to install the theme without running this command for those who wants :wink:

**Comment by alvatip** [comment]
It should work without creating the cache files. I created an argument (-g) to the script to install the theme without creating these cache files :wink:

**Comment by MolassesLover** [comment]
> It should work without creating the cache files. I created an argument (-g) to the script to install the theme without creating these cache files :wink: 

Thank you so much! This is going to help so much with debugging.
