### ISSUE TITLE
The terminal icon looks bad with Nordic-darker and XFCE

### ISSUE THREAD

**Issue by hacker-biba** [alvatip/Nordzy-icon#78]
Hi, [alvatip](https://github.com/alvatip)!
I really appreciate your work. I'm new in Linux and your icon theme and Nordic made me stop theme hopping :)

I'm using 1366x768 screen, Nordic-darker theme and XFCE

My issue in the first place is that the terminal icon on panel looks little weird. Like someone cut it carelessly from somewhere using Photoshop. It's because of white rim around the terminal's logo. I know it's not your fault, it goes from parent WhiteSur icon theme.

![Screenshot_2022-09-23_20-16-28](https://user-images.githubusercontent.com/81816655/192027107-7978e609-b8ae-43c7-be22-04cc817b4132.png)

Secondly the icon looks blurred at window's title

![Screenshot_2022-09-23_20-19-56](https://user-images.githubusercontent.com/81816655/192027343-9dab5ad5-fbf7-41a0-9153-0cc345f383d4.png)

**Comment by MolassesLover** [comment]
This is likely because of the backdrop being coloured with `#2e3440`.
I made issue https://github.com/alvatip/Nordzy-icon/issues/71 for this reason.

**Comment by alvatip** [comment]
I redesigned the terminal icon, this should fix the first issue :wink: Could you try the new one and tell me if it looks fine ? also does the second issue still appear ?
Thanks!

**Comment by MolassesLover** [comment]
> @hacker-biba, I redesigned the terminal icon, this should fix the first issue wink Could you try the new one and tell me if it looks fine ? also does the second issue still appear ? Thanks!

It reads so much worse on Nordic GTK, or a desktop with a Nord background.I really like the style but it just doesn't suit the Nord ecosystem. Do you think you could add the outline back in?

**Comment by alvatip** [comment]
I will look for another solution then

**Comment by MolassesLover** [comment]
Awesome, take your time, and thanks for all the good work!

> I will look for another solution with the White border then wink

**Comment by alvatip** [comment]
I modified the terminal icon, giving it a thicker border to avoid this weird look like it was cut in photoshop and keeping the white border. This is a first try, so the size of the border and the symbol inside the icon might still have to be adjusted. 

Another solution could be the removal of the white border and inversion of the colors (so white background and black symbol) but when I think of terminal icon, dark is the primary color that pops in my mind haha

Tell me what you think! 

Thanks :wink:

**Comment by hacker-biba** [comment]
@alvatip,
The icon looks great
![Screenshot_2022-11-17_10-51-24](https://user-images.githubusercontent.com/81816655/202393903-6c418861-8e2f-421b-ab61-c88acbdf697e.png)
![Screenshot_2022-11-17_10-52-00](https://user-images.githubusercontent.com/81816655/202393936-3feb174a-698f-4695-b461-8591678fb044.png)
![Untitled](https://user-images.githubusercontent.com/81816655/202393980-8709c183-d1bd-46ac-a338-c6758223eaf0.jpg)


Thanks!

**Comment by alvatip** [comment]
Good news! 
Thanks for confirming that it looks fine ;)
