### ISSUE TITLE
New icon for Pycharm

### ISSUE THREAD

**Issue by AdrienGranger** [alvatip/Nordzy-icon#87]
Thanks for the awesome job !
Could you add an icon for Pycharm ? That would be very cool.
thanks a lot

**Comment by MolassesLover** [comment]
I can't seem to find a way to make the gradient look good. I tried to use a mesh fill but GNOME doesn't support it.

![pycharm](https://user-images.githubusercontent.com/60114762/194595723-be1b34fc-2728-4d72-910b-3343f6509cf0.svg)

Thoughts?

**Comment by alvatip** [comment]
Thanks @MolassesLover
