### ISSUE TITLE
[BUG] Invalid GTK cache

### ISSUE THREAD

**Issue by akkesm** [alvatip/Nordzy-icon#9]
**Describe the bug**
gtk-update-icon-cache fails with output:
```
gtk-update-icon-cache: The generated cache was invalid.
```
Removing `src/apps/scalable/preferences-system-splash (copy).svg` fixes the issue. The filename contains invalid characters.

**To Reproduce**
Run the installer.

**Expected behaviour**
A valid cache.

**Desktop**
NixOS, Sway. Tested both as a Nix package and with the normal installer.

**Comment by alvatip** [comment]
Hi, 
Indeed, I forgot to remove this file while working on them. 
Got the same issue on fedora and ubuntu. Both solved by removing the copy file.
I updated the theme by removing the issue should be fixed now.

Thanks for reporting it.
Have a nice day :wink:

**Comment by akkesm** [comment]
Thank you for the fix!

**Comment by alvatip** [comment]
You are very welcome!
