### ISSUE TITLE
[BUG]No way to install it to fedora KDE

### ISSUE THREAD

**Issue by muhrmart** [alvatip/Nordzy-icon#92]
**Describe the bug**
Import to Fedora KDE Spin not possible. 

**To Reproduce**
Steps to reproduce the behaviour:
Installation via Discover -> no response, not available in configuartion

Download and import of tar file -> Error message: no  valid archive

**Screenshots**
![grafik](https://user-images.githubusercontent.com/106246361/196398827-7d842e9e-89f6-4095-a3f5-43cc6f7cdd8a.png)

**Desktop**
Distro: Fedora, 
DE: KDE PLASMA

**Comment by alvatip** [comment]
Hi, 
Thanks for reporting :+1: 
I will install the KDE desktop on my fedora system to try this. For now, the archives are working perfectly fine on fedora + gnome
In the meanwhile, did you already try installing another icon theme from discovery ?
Thanks

**Comment by muhrmart** [comment]
In fact I am switching icons quite often ;) . First time this happened. Tested it right toda with tela icons and Zafiro Nord Dark

**Comment by alvatip** [comment]
I just updated the icon theme, could you try it and confirm that the issue is fixed ? (or not fixed)
Thanks

**Comment by alvatip** [comment]
Great, many thanks for reporting!
