### ISSUE TITLE
[ICON]

### ISSUE THREAD

**Issue by muhrmart** [alvatip/Nordzy-icon#93]
Application name: keepass, newsflash, discover, retroarch, joplin
Icon name if you know it: ?
Original icon image: ?
Use tray?
Small description and/or a link to the official webpage:

Thanks in advance

**Comment by alvatip** [comment]
I will work on that this week 😉

**Comment by alvatip** [comment]
All should be fine now! :+1: 
If something is wrong/missing, feel free to re-open this issue :wink:

**Comment by muhrmart** [comment]
![Screenshot_20221020_185615](https://user-images.githubusercontent.com/106246361/197012514-afd0a084-07cb-4f4f-a196-75ade9d2c1ae.png)
Hi it  keestore seems not to work. the size of thunderbird looks also not right :) 
Thanks in advance

**Comment by alvatip** [comment]
I will make an icon for keestore, this is because you mentioned keepass, but not keestore :laughing: 
I will also have a look to the thunderbird icon, to see if the size is maybe wrong, but it should not be the case

**Comment by alvatip** [comment]
could you confirm that keepass does display properly now ? Thanks very much :smile:
