### ISSUE TITLE
[ICON]Missing icons for Waterfox, Kde Connect Tray, Geary, Diodon, Indicator-notifications Tray and Audacity

### ISSUE THREAD

**Issue by AngelSherry** [alvatip/Nordzy-icon#94]
Application name: **Waterfox** 
Issue: **Missing icon**
Icon name if you know it: **waterfox-g, waterfox-classic, waterfox**
Original icon image:
![waterfox-g](https://user-images.githubusercontent.com/53128145/196659046-f96ef7a6-b3d4-48d8-8e26-d0dd13b2af60.png)
Use tray? **No**
Small description and/or a link to the official webpage:
[Waterfox Official](https://www.waterfox.net/)

Application name: **Kde Connect**
Icon name if you know it: **kdeconnect-tray**
Issue: **Missing tray icons**
![圖片](https://user-images.githubusercontent.com/53128145/196662405-141b4527-46de-408c-8557-cc1de429b3bf.png)
Original icon image: 
**Light Version**
![kdeconnect-tray](https://user-images.githubusercontent.com/53128145/196660798-7deb9cb3-fa77-4609-86db-ff6feaa047bf.svg)
**Dark Version**
![kdeconnect-tray](https://user-images.githubusercontent.com/53128145/196660962-f416e7aa-6200-4cf2-a432-1a3bc7c77cbf.svg)
Use tray? **Yes**
Small description and/or a link to the official webpage:
[Kde Connect Official](https://kdeconnect.kde.org/)

Application name: **Geary**
Issue: **Only monochrome symbolic icon is offered**
![圖片](https://user-images.githubusercontent.com/53128145/196662833-8e9dc23b-8ccb-4e9e-9edf-381f40332740.png)
Icon name if you know it: **org.gnome.Geary, geary, org.gnome.Geary-symbolic**
Original icon image: 
**geary**
![geary](https://user-images.githubusercontent.com/53128145/196662938-34964deb-fbfc-42aa-bc14-434a66ae54b9.svg)
**org gnome Geary**
![org gnome Geary](https://user-images.githubusercontent.com/53128145/196662971-7933c0e0-87e3-4b55-a6f5-b4d2e88363bc.svg)
**org gnome Geary-symbolic**
![org gnome Geary-symbolic](https://user-images.githubusercontent.com/53128145/196663527-999d1cc7-1eaa-448e-b07d-00f451055af4.svg)
Use tray? **Yes**
Small description and/or a link to the official webpage:
[Geary Wiki](https://wiki.gnome.org/Apps/Geary)

Application name: **Diodon**
Issue: **Missing icon**
Icon name if you know it: **diodon, diodon-panel**
Original icon image: 
![diodon](https://user-images.githubusercontent.com/53128145/196666305-e39d6d86-4cd2-476e-8c81-b05f5997f609.svg)
Use tray? **Yes** 
Small description and/or a link to the official webpage:
[Diodon Github](https://github.com/diodon-dev/diodon)

Application name: **Recent Notifications**
Issue: **Missing tray icons**
![圖片](https://user-images.githubusercontent.com/53128145/196669158-bded2439-99f5-4d70-96e5-895046d30ba5.png)
Icon name if you know it: **indicator-notification-close-deselect, indicator-notification-close-select, indicator-notification-read, indicator-notification-read-dnd, indicator-notification-unread, indicator-notification-unread-dnd**
Original icon image: 
![indicator-notification-close-deselect](https://user-images.githubusercontent.com/53128145/196668527-9a854317-d084-4147-8fe2-b70b29030465.svg)
![indicator-notification-close-select](https://user-images.githubusercontent.com/53128145/196668533-38d0ae90-fc43-4a17-8b17-882b9e883aee.svg)
![indicator-notification-read](https://user-images.githubusercontent.com/53128145/196668537-cfdef0e6-1255-4264-94ad-3c4f3416f04c.svg)
![indicator-notification-read-dnd](https://user-images.githubusercontent.com/53128145/196668540-b675d2be-ccf7-409a-a0a0-207d9c84a98c.svg)
![indicator-notification-unread](https://user-images.githubusercontent.com/53128145/196668546-5abdcecb-db5d-445b-8c31-be4f55c471c6.svg)
![indicator-notification-unread-dnd](https://user-images.githubusercontent.com/53128145/196668548-b77504c6-1f50-4191-9be2-8a7e5b21ef2a.svg)
Use tray? **Yes**
Small description and/or a link to the official webpage:
[indicator-notifications](https://github.com/trism/indicator-notifications)

Application name: **Audacity**
Issue: **Missing icon**
Icon name if you know it: **audacity**
Original icon image: 
![audacity](https://user-images.githubusercontent.com/53128145/196683717-e39785db-7679-4ba1-bf88-424fce72ccb6.svg)
Use tray?  **No**
Small description and/or a link to the official webpage:
[Audacity Official](https://www.audacityteam.org/)

**Comment by alvatip** [comment]
Thanks for this, I will complete the previous request then I will work on this one :wink:

**Comment by alvatip** [comment]
Hey, 
waterfox, geary and the kde connect tray should be fine now.
I will finish the others this weekend!

**Comment by alvatip** [comment]
All the icons should be present by now, 
if something is not working (or, ugly, can sometimes happen), feel free to reopen this issue and I will gladly bring the needed modification
